### ISSUE TITLE
Requesting Assistance

### ISSUE THREAD

**Issue by krsna-rand** [rust-lang-nursery/mdBook#1002]
Hey all. I hope y'all are well and in good mood whe you receive this.
I have been hacking away for 12+ hours your searcher.js and the generated index.html but Im unsuccessful atm.

All I want to do is:
Remove the toggle button and always show the search bar.
Results are displayed only after pressing enter. Instead of a live search. I have a large data set and this will make UX much better.

If you find this good, I certainly appreacite it very much.

Ive been reading the code but Im not familiar with JS. 
I gave it my best shot.

Thank you very much for your time.

PS
I used your software for the following sites: (very large data sets)

[bg-ai.github.io](https://bg-ai.github.io)
[srimad-bhagavatam.github.io](https://srimad-bhagavatam.github.io)

I had to nest each chapter into its own book in order to achieve the sidebar functionality that I wanted in order to provide a good UX .

**Comment by krisradio** [comment]
My search function is broken for unrelated reasons right now, so I don't know if the following technique interferes with search functionality in any way. But it definitely _does_ make the search bar always-on and remove the search icon from the toolbar. I hope this helps you. :)

### Editing search.js
The main functions you need to look at are in searcher.js. They are `showSearch`, on line 362, and `searchIconClickHandler`, on line 385.

`showSearch`, when passed a true argument, removes the hidden attribute from the search-wrap div. We'll do that from the start, so you don't need that line. showSearch also sets the aria-exoabded attribute on the searchIcon, but with always-on search we can remove searchIcon, so in the end, the method showSearch can be deleted.

`searchIconClickHandler` can also be deleted, as it just calls showSearch and scrolls to/selects the search bar. You don't need that anymore, so delete `searchIconClickHandler`. 

Finally, Line 258 of searcher.js adds an event listener to call `searchIconClickHandler` on clicking the element searchIcon. You'll want to delete that line, too. Here's the whole line: 

```
searchicon.addEventListener('click', function(e) { searchIconClickHandler(); }, false);
```

### Editing index.hbs
You'll probably want to remove searchIcon from index.hbs, which you can do by deleting lines 113-116 from index. These are the lines to delete: 

```
{{#if search_enabled}}
<button id="search-toggle" class="icon-button" type="button" title="Search. (Shortkey: s)" aria-label="Toggle Searchbar" aria-expanded="false" aria-keyshortcuts="S" aria-controls="searchbar">
<i class="fa fa-search"></i>
</button>
```

You'll want to also remove the `class="hidden"` attribute, on line 136 of index.hbs. This will make your search bar always-visible. This is the whole line to edit by removing `class="hidden"`: 

```
<div id="search-wrapper" class="hidden">
```

**Comment by krsna-rand** [comment]
Hey this is great! Thank you very much for your time! 
I dont think its broken, I like it very much, it definitely works as I want to.
If you have some time you can see it in action.
(Your search in action)[https://krsna-rand.github.io]
Select 'Random' from the menu.

**Comment by krisradio** [comment]
You're welcome, it was a fun challenge. 

I don't have a donation page really, but you could check out my blog at [krisrad.io](https://krisrad.io), and share it with anyone into decentralization and the peer-to-peer web. I would very much appreciate that!

As for disabling live search, probably adding some keyboard detection in the `doSearch` function (line 437) of searcher.js could do it. Javascript isn't my strong suite however, so I'm not sure exactly how.

Thanks for sharing your site too, interesting to see some discussion on the 'Me' in the wild! I was just reading about that in _Snow Crash_, they are powerful concepts indeed. I really liked this bit on the latest entry 

> In the beginning one must have a preliminary desire for self-realization.  
> This will bring one to the stage of trying to associate with persons who are spiritually elevated.

Kind of like us bumping into each other here eh? 

Best of luck with your development! And don't forget to do the folks at mdbook a favor and mark this issue as closed when you are satisfied!

**Comment by krsna-rand** [comment]
I will certainly do that. Maybe an Amazon gift card? I do appreciate to you. Im glad you found the site of interest. Stay tuned in.  Indeed providence is controlled. No such thing as luck. Take care of the Me inside
