### ISSUE TITLE
FontAwesome icons not rendered locally

### ISSUE THREAD

**Issue by ngirard** [rust-lang-nursery/mdBook#1009]
I'm currently working on the documentation of [Ion](https://gitlab.redox-os.org/redox-os/ion), whose sources can be found [here](https://gitlab.redox-os.org/redox-os/ion/tree/master/manual) and published html pages [there](https://doc.redox-os.org/ion-manual/).

Oddly enough, while the published pages do display the FontAwesome icons correctly, I can't see them when I render the manual locally (Ubuntu 19.04, with FontAwesome fonts installed).

Do you have any idea why ?

Thanks in advance !

**Comment by ehuss** [comment]
Are you using `mdbook serve` to view locally?  Are there any error messages in the browser console?  Does the network tab in the browser's developer tools show it downloading FA?

**Comment by ngirard** [comment]
Aww...stupid me... I was just building the manual and opening the pages via my browser. `mdbook serve` obviously solved my problem.

Thanks for your help, @ehuss !
