### ISSUE TITLE
offline docs doesnot show symbols proper on firefox

### ISSUE THREAD

**Issue by Karuturirs** [rust-lang-nursery/mdBook#1014]
The offline docs does not show symbols properly such as navigation to previous page, next page, table of content, change theme, search and print this book in firefox browser only.

> rustup docs --book
open docs in firefox.

//version

> rustc --version --verbose
    rustc 1.37.0 (eae3437 2019-08-13)
    binary: rustc
    commit-hash: eae3437
    commit-date: 2019-08-13
    host: x86_64-apple-darwin
    release: 1.37.0
    LLVM version: 8.0

Firefox version: 68.0.1(64-bit)

attaching file
<img width="1437" alt="Screen Shot 2019-08-19 at 7 45 01 PM" src="https://user-images.githubusercontent.com/7746544/63356088-0a405680-c31c-11e9-9476-a9fe36a6676c.png">

**Comment by ehuss** [comment]
I think you need to update to Firefox 68.0.2. From the release notes:

> Allow fonts to be loaded via file:// URLs when opening a page locally (bug 1565942)

**Comment by Karuturirs** [comment]
Updated the my firefox to 68.0.2 working fine. 
Thanks. Closing it.
