### ISSUE TITLE
How to add line numbers to default playpen?

### ISSUE THREAD

**Issue by adamchalmers** [rust-lang-nursery/mdBook#1028]
I notice that the Ace editor can be configured to show/hide line numbers by setting `showLineNumbers`, but `mdbook` explicitly [sets this to false](https://github.com/rust-lang-nursery/mdBook/blob/master/src/theme/playpen_editor/editor.js#L13).

I couldn't see a way to pass configuration from my `mdbook` project's `.toml` to override this. IMO it would be a big improvement if book authors could configure their editor to show or hide line numbers.

**Comment by andymac-2** [comment]
@Michael-F-Bryan  I would like to take on this issue. I apologize if you're the wrong person to ping.

**Comment by Michael-F-Bryan** [comment]
Thanks for volunteering to help, @andymac-2!

At a glance, you would need to add a new `show-line-numbers` option to [the `HtmlConfig`][1] so it's configurable from `book.toml` under the `output.html` table. 

From there you'll have to figure out how to tell Ace to show/hide line numbers (probably by playing with from the generated HTML, [around here somewhere][2]). The context info passed to each handlebars template is done [in the `make_data()` function][3].

I didn't have much to do with the frontend and am not actively working on `mdbook`, but @ehuss or @Dylan-DPC may be able to point you in the right direction. 

[1]: https://github.com/rust-lang-nursery/mdBook/blob/b4bb44292d707c720dc75851500b3249d3a93ad3/src/config.rs#L418
[2]: https://github.com/rust-lang-nursery/mdBook/blob/b4bb44292d707c720dc75851500b3249d3a93ad3/src/theme/index.hbs#L234

**Comment by andymac-2** [comment]
Already done ;) PR  #1035 has the required implementation, and updates the docs accordingly. Thanks for your help! You're the first name that pops up on the `CONTRIBUTORS` file
