### ISSUE TITLE
Upgrade to Font Awesome 5

### ISSUE THREAD

**Issue by srimad-bhagavatam** [rust-lang-nursery/mdBook#1031]
**fa fa-search** icon is broken for v4.7

https://fontawesome.com/v4.7.0/icon/search

**Comment by Dylan-DPC** [comment]
Hi. Is it possible for you to send a PR that fixes it?

**Comment by krsna-rand** [comment]
I wish I could but I'm just an end-user. I tried to manually use v5 and it doesnt work either. I emailed FontAwesome support.

**Comment by krsna-rand** [comment]
The folks at FontAwesome have fixed the issue. Please close this.
Thank you very much for all the hard work and love you put into this great software.
