### ISSUE TITLE
Support for non-menu pages

### ISSUE THREAD

**Issue by JensRantil** [rust-lang-nursery/mdBook#1034]
We just noticed that `mdbook` doesn't compile/build pages which are not linked from `SUMMARY.md`. Background here is that we would like some pages which are only accessible through search and/or links from other pages.

So far we haven't found a way to generate these pages and found no issue adressing this. Let us know if this a duplicate.

**Comment by ehuss** [comment]
Thanks for the report. I think this is more or less #830, so I'm going to close in favor of that.
