### ISSUE TITLE
[Feature Request] Copy code button should be optional

### ISSUE THREAD

**Issue by DhruvDh** [rust-lang-nursery/mdBook#1043]
The copy code button functionality should configurable in `book.toml`.

Particularly on mobile, the copy button is an eye-sore and is mostly useless, since no one is going to be able to make use of copied code on non-computers. On mobile the button is also relatively large compared to the rest of the content and seems to take away from what is otherwise a very clean and minimal design.

Also, for some books, the code blocks then to contain code that is incomplete or just are meant to show a skeleton of how actual code might look like and there isn't any value in copying that code.

It seems the way the code is written in `index.js` it is non-trival to get rid of this functionality; getting rid of the code that creates the copy button ends up breaking the functionality of other buttons, such as the sidebar. It could just be that I do not understand the way `index.js` is structured enough to be able to remove this functionality.

Setting the css for `.fa-copy.fa` to `display: none` works, but feels like a dirty hack.

**Comment by andymac-2** [comment]
@ehuss I'd like to claim this issue

**Comment by Dylan-DPC** [comment]
@andymac-2 sure go ahead
