### ISSUE TITLE
Better message when `mdbook clean` is run on clean workspace

### ISSUE THREAD

**Issue by amanjeev** [rust-lang-nursery/mdBook#1046]
Currently, if you run `mdbook clean` twice, you get the following error: 

```
$ mdbook clean
2019-10-02 20:18:03 [ERROR] (mdbook::utils): Error: Unable to remove the build directory
2019-10-02 20:18:03 [ERROR] (mdbook::utils):    Caused By: No such file or directory (os error 2)
```

Would it make sense to show a better message to the user when running `mdbook clean` on an already clean workspace? 

If you think this proposal makes sense, I could perhaps do this but I would need suggestions from you. If you think I am missing something and this is not a good idea, please close this issue.

Thank you.

**Comment by rnitta** [comment]
How about replacing [`fs::remove_dir_all`](https://github.com/rust-lang-nursery/mdBook/blob/a6f317e352855fe058af82d18cae5541c6b356d3/src/cmd/clean.rs#L32) with [`fs::remove_dir_content`](https://github.com/rust-lang-nursery/mdBook/blob/d371001ab82fb13b1457ca0df9cc7ecd773414b5/src/utils/fs.rs#L78-L90) like [here](https://github.com/rust-lang-nursery/mdBook/blob/a873d468711e14fc291b69f23f50b6769f9e6dab/src/renderer/markdown_renderer.rs#L29-L32) or [here](https://github.com/rust-lang-nursery/mdBook/blob/ed95252f05c25800e952edc0e186e76b52de4ccb/src/renderer/html_handlebars/hbs_renderer.rs#L285-L288)?

**Comment by amanjeev** [comment]
@rnitta Thank you. I would like to know if it is ok to not remove the build directory? If you see, as an example, `cargo clean` which removes the `target` directory. What do you think?

**Comment by ehuss** [comment]
I think it would be good if it didn't print anything if the output directory doesn't exist, and exited 0.  Also, unless you see a reason, I think it would be fine to just delete the directory, too, I don't see a reason to keep an empty directory around.  That is, just wrap the `fs::remove_dir_all` with a check if the path exists.

**Comment by amanjeev** [comment]
@ehuss I think that is also consistent with `cargo clean`. Will do!
