### ISSUE TITLE
Ctrl + Enter playpen shortcut

### ISSUE THREAD

**Issue by vvanpo** [rust-lang-nursery/mdBook#1049]
The [rust-by-example](https://doc.rust-lang.org/stable/rust-by-example/hello.html) documentation invites us to use "ctrl + enter" to run playpen code, but this doesn't work (at least, not for macOS in either Chrome nor Safari).

**Comment by rnitta** [comment]
It doesn't seem to be issue of mdbook.

```rust
// or if you prefer to use your keyboard, you can use the "Ctrl + Enter" shortcut
```

It may be the dead comment of [rust  by example](https://github.com/rust-lang/rust-by-example).

Rust-by-example  used to be built with gitbook, but currently using mdbook.
At that time, the command `Ctrl-Enter` would work, but it seems that the feature had lost in the migration from gitbook to mdbook.

https://github.com/rust-lang/rust-by-example/commit/f39d8182ae8f093aeff844a04f9c9f66e3bcbb15


Though correcting the comment of rust-by-exmaple is reasonable,
there is the way to fix the problem by adding command to default mdbook's theme; https://github.com/rust-lang-nursery/mdBook/pull/1066

:D
