### ISSUE TITLE
Appveyor is not working

### ISSUE THREAD

**Issue by ehuss** [rust-lang-nursery/mdBook#1057]
Appveyor seemed to stop working about 2 weeks ago with:

> Error fetching YAML configuration file from the repository. Make sure AppVeyor is authorized to access your gitHub account: AppVeyor GitHub App is not installed for account "rust-lang-nursery".

**Comment by weihanglo** [comment]
Maybe we can migrate our CI/CD process to GitHub Action or Azure pipeline. Unifying infra to a single services seems to be a great direction to me.

**Comment by ehuss** [comment]
Yea, we are migrating to GitHub Actions.  I have a branch with all the changes, I just need to do some testing on it.  I got my personal account in the beta a couple days ago, and I just need some time to test it.  I also need some time from the infra group to enable it and encrypt some tokens.  I'll try to get it going soon.

**Comment by ehuss** [comment]
Fixed via #1071.
