### ISSUE TITLE
Remote links do not work as expected

### ISSUE THREAD

**Issue by MageSlayer** [rust-lang-nursery/mdBook#1060]
Trying to use remote links to other .md's sections results in creating files instead (e.g. "intrinsics.md#link" filename)

e.g. when writing summary as:
```
  - [Intrinsics](./intrinsics.md)
    - [Intrinsics](./intrinsics.md#link)
```

Local links work fine though.

Both 0.3.1 and git versions checked.

**Comment by ehuss** [comment]
Thanks for the report!  I think this is a duplicate of #167, so I'm going to close in favor of that.
