### ISSUE TITLE
Underscores in Ace Editor are not rendered with Ace default CSS

### ISSUE THREAD

**Issue by davidomarf** [rust-lang-nursery/mdBook#1061]
Hi. I opened an issue in another repository (https://github.com/rust-lang/rust-by-example/issues/1279) thinking it belonged there. 

However, I found mdBook, and followed the documentation, which is also implemented with mdBook, and found the same problem:

![image](https://user-images.githubusercontent.com/22549761/66428005-ce03ab00-e9da-11e9-967f-f60fedaa9122.png)

**Comment by davidomarf** [comment]
I zoomed in to a 110% and they're rendered:
![image](https://user-images.githubusercontent.com/22549761/66428252-56824b80-e9db-11e9-81ae-9b1a700640e2.png)

So I should also add the resolution as reference: `1366 x 768`.

Even if they're rendered, I still make the suggestion of the font to be replaced.

**Comment by ehuss** [comment]
It sounds like you have a bad font installed?  What happens if you uninstall it?  Or install one of the other fonts that have higher priority?

It's also helpful if you include which browser, OS, versions, etc. that you have tried.

**Comment by davidomarf** [comment]
Sorry, I didn't wanted to fill this issue with the same content I wrote in the other issue I linked. 

I'm copying it directly from there, making some changes to remove irrelevant information.

I just tried to see the same pages in Firefox and found no problem. 

The fact that the zoom fixed the problem in Chrome, makes me think that it's also the resolution that is causing problems.

---
### `font` attribute

This is the default style for Ace blocks:
![image](https://user-images.githubusercontent.com/22549761/66425440-4d8e7b80-e9d5-11e9-87cc-ad11288058a1.png)

When supressing the `font` attribute in `.ace_editor`, the underscore renders properly:
![image](https://user-images.githubusercontent.com/22549761/66425520-82023780-e9d5-11e9-818d-ad00c4863224.png)

[WhatFont][whatfont] reports that the font used is monospace:
![image](https://user-images.githubusercontent.com/22549761/66425727-fa68f880-e9d5-11e9-8248-f1a9972767c0.png)

However, when I force monospace to be the chosen font, it works properly:
![image](https://user-images.githubusercontent.com/22549761/66425701-e45b3800-e9d5-11e9-9dd5-e1ffaadb8625.png)

I checked for the installed functions in my OS. This is the result:

```sh
$ fc-list | grep -i "Monaco"                                                                                                                               
## nothing

$ fc-list | grep -i "Menlo"          
## nothing

$ fc-list | grep -i "Ubuntu"         
## nothing

$ fc-list | grep -i "Consolas"       
## nothing

$ fc-list | grep -i "source-code-pro"
/usr/share/fonts/adobe-source-code-pro/SourceCodeVariable-Roman.otf: Source Code Variable:style=Light
## ... several more lines
```

### `'source-code-pro', monospace`

Apparently, that's the problematic **combination**. If I only leave `source-code-pro` in the list of fonts to use, it defaults to `serif`:
![image](https://user-images.githubusercontent.com/22549761/66426245-0903df80-e9d7-11e9-99b0-ca8f5d1f1e84.png)
 

### `'Source Code Pro'`

If I replace `'source-code-pro'` with `'Source Code Pro'`, it renders properly:

![image](https://user-images.githubusercontent.com/22549761/66426520-9e06d880-e9d7-11e9-865b-3b1a61ffb791.png)

## Proposed solutions
a. Replace `'source-code-pro'` with `'Source Code Pro'` with a script (since it's not provided and generated from [ace.js script][acejs]).
b. Add `!important` to `code { font-family }` in `general.css` 

[functions]: https://doc.rust-lang.org/rust-by-example/fn.html
[whatfont]:https://chrome.google.com/webstore/detail/whatfont/jabopobgcpjmedljpbcaablpmlmfcogm?hl=en
[acejs]:https://doc.rust-lang.org/rust-by-example/ace.js

---

If needed or relevant, this is my environment:
OS: Manjaro 18.1.0
Chrome: 77.0.3865.90

**Comment by davidomarf** [comment]
I originally thought you didn't read the linked issue, but reading your comment again, makes me think you did.

Should installing the other higher-priority fonts be considered an appropiate fix? I feel this is a very particular case, that affects Chrome on (at least) 1366 x 768 displays, and when you don't have either of Monaco, Menlo, Ubunto Mono, or Consolas font installed.

**Comment by itsmeolivia** [comment]
I'm running Chrome Version 78.0.3904.108 (Official Build) (64-bit) on a linux 4.19.67-2rodete2-amd64
 OS and I do not see underscores either. I can open a new issue if you prefer

**Comment by ehuss** [comment]
@itsmeolivia Which version of mdbook are you using?  Which linux distribution is that?

**Comment by albfan** [comment]
I think this is related https://github.com/ajaxorg/ace/issues/4000#issuecomment-559189283
