### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by azerupi** [rust-lang-nursery/mdBook#11]
Add tests in the code. 

I have never really used tests, if someone could help me make meaningful tests that would be wonderful!

**Comment by azerupi** [comment]
On hold, is a part of #90

**Comment by rbuckland** [comment]
As there are tests - this issue should be closed now. If there are any specific tests that are thought needed (that I am sure there are), suggest a new issue is raised.

**Comment by mattico** [comment]
Agreed!
