### ISSUE TITLE
iOS jumping to page top is broken

### ISSUE THREAD

**Issue by aaaxx** [rust-lang-nursery/mdBook#185]
A minor nit but I thought I'd report it anyway.

Something, in javascript most likely, breaks the standard functionality in iOS of jumping to the top of the page when the top of the screen is tapped.

**Comment by azerupi** [comment]
Thanks for reporting! I will probably need some help for this one though, as I have no iOS device to test this on :)

**Comment by aaaxx** [comment]
Well, I can test it if you can figure out what's causing it.

**Comment by Dylan-DPC** [comment]
This was fixed in #310
