### ISSUE TITLE
Generated HTML has CRLF line endings, on a Mac

### ISSUE THREAD

**Issue by zackw** [rust-lang-nursery/mdBook#234]
The HTML generated by mdbook has CRLF line endings.  The browser doesn't care, and if I were on Windows it would be the Right Thing, but I'm on a Mac and it makes it annoying to look at the HTML in e.g. the stock `vi`.  Can we please have platform-appropriate line endings?

**Comment by steveklabnik** [comment]
Sure.

**Comment by azerupi** [comment]
I'm not sure how that happend, I never use windows and I can't imagine myself writing code that would add CRLF line endings. I would have to check where those come from, maybe someone sneaked it in with a PR or it comes from a dependency.

**Comment by steveklabnik** [comment]
Yeah, I found the idea confusing as well, but we should figure it out.

**Comment by ollie27** [comment]
Looks like this is a problem with the 0.0.18 version published to crates.io. The source files have CRLF line endings and this is a problem because `index.hbs` has CRLF meaning the generated HTML gets a mixture of CRLF and LF line endings.

**Comment by azerupi** [comment]
Aah I see, thanks for finding the source of the problem!

**Comment by steveklabnik** [comment]
Interesting, this is probably my fault then. I should submit a .gitattributes to make sure windows users don't accidentally introduce this...

**Comment by steveklabnik** [comment]
I submitted https://github.com/azerupi/mdBook/pull/236, but I can't actually find a CR in index.hbs, maybe it was fixed in the meantime? @zackw if you use the latest master of mdbook, do you still see this?

**Comment by ollie27** [comment]
It's only in the version published to crates.io that's broken. I'm guessing you published from Windows and had autocrlf enabled in git. I suggest disabling autocrlf as it just breaks things.

**Comment by ehuss** [comment]
I think this has long since been fixed.
