### ISSUE TITLE
Make parse_summary public?

### ISSUE THREAD

**Issue by Rufflewind** [rust-lang-nursery/mdBook#265]
Could `parse_summary()` be made public?  Currently in order to parse `SUMMARY.md` it’s necessary to run either `init()` or `test()`, which is undesirable due to their other side-effects.

**Comment by azerupi** [comment]
I think it would be good to make it public too, however... It is in a terrible state right now so I am not sure how useful it would be.

**Comment by Michael-F-Bryan** [comment]
The summary parser was updated in #491, with the docs for the `mdbook::book` module being fleshed out in be4654c9c2. The equivalent of `parse_summary()` will be available in the next release (either v0.0.29` or `0.1.0`) :tada:
