### ISSUE TITLE
Make mdBook more contributor friendly

### ISSUE THREAD

**Issue by azerupi** [rust-lang-nursery/mdBook#270]
I just watched [this excellent talk](https://www.youtube.com/watch?v=AHprJNUCgQ0) by @Manishearth and decided to apply some of his tips to make this repository more contributor friendly!

Here are the things we should do:

### Issues
- [x] Reorganize the labels in a very similar way as most big Rust projects (e.g. Rust, Servo, Clippy, ...). Labels are grouped: Area, Experience, Meta, Status and Type. Other groups can be made if need be.
- [x] Go through all the open issues, remove the old labels and apply the new ones
- [x] Remove the old labels

### Contribution File
- [x] Create a new `CONTRIBUTING.md` file
- [x] Explain that style fixes need to modify the Stylus files and rebuild the CSS
- [ ] Explain how to run Clippy and Rustmft. They should not be a requirement, but it's nice if the code is constantly kept tidy
- [ ] Mention the different useful ways a beginner could help out: Documentation, Tests, Examples, Updating dependencies, E-Easy issues

**Comment by azerupi** [comment]
I was able to go as far as issue 235 tonight. I will continue to triage the issues tomorrow.

**Comment by azerupi** [comment]
I've gone through all the open issues and relabled them. Old labels are now gone, new labels are much more explicit.

**Comment by steveklabnik** [comment]
This is wonderful
