### ISSUE TITLE
Support touch gestures on mobile to open and close the sidebar

### ISSUE THREAD

**Issue by azerupi** [rust-lang-nursery/mdBook#274]
Mobile users could use touch gestures like swipe right and left to open and close the sidebar. This would be way more ergonomic than the little hamburger menu they need to use.

This would fix issue #125

**Comment by marti1125** [comment]
@azerupi I would like to work on this =D

**Comment by azerupi** [comment]
Great! It's all yours, if you need any help let me know :)

**Comment by marti1125** [comment]
@azerupi could you give some instructions how I can get started ? please

**Comment by azerupi** [comment]
I have never done any touch development myself, but I would look into JavaScript librairies like  [JQuery Mobile](https://jquerymobile.com/) or [Hammerjs](http://hammerjs.github.io/).

Particularily, [this demo](http://demos.jquerymobile.com/1.3.2/examples/panels/panel-swipe-open.html) might be of interest. :)

**Comment by Michael-F-Bryan** [comment]
Fixed in #474
