### ISSUE TITLE
Release a 0.1.0 version ?

### ISSUE THREAD

**Issue by azerupi** [rust-lang-nursery/mdBook#275]
I think we should release a 0.1.0 version even though we don't really have breaking changes. The rationale is that currently it is impossible to distinguish simple bug-fix releases with more important releases because we only have the patch version to play with. I chose to begin at 0.0.1 at the time, but I recognize that it wasn't such a good idea.

At the same time, we could take advantage of this release to polish and push the TOML configuration file over the json config. Currently, the two live happily together, but I would like to deprecate the json config. 

What are your thoughts on this?  @steveklabnik @frewsxcv

**Comment by steveklabnik** [comment]
Yes, I personally am a fan of doing 0.x.0 releases during development, rather than the 0.0.z releases we've been doing.

**Comment by frewsxcv** [comment]
ditto Steve's comment

**Comment by azerupi** [comment]
Perfect, so I will take a look at the TOML configuration and see what needs to be done before we can push it as a replacement for the JSON config.

**Comment by budziq** [comment]
Hi, @azerupi How are we on the 0.1.0 front? There is quite a lot of demand for it and some downstream repos started backporting fixes. I'm back from holidays and even though I will need to step up in rust-cookbook and rust-skeptic maintenance (so even less free time) I would love to help in making the release happen! 

cc https://github.com/azerupi/mdBook/issues/379

**Comment by azerupi** [comment]
There is still some documentation work to do, but other than that we can release 0.1.0
We should at least do #368 before the release

**Comment by budziq** [comment]
@azerupi great! I'll schedule some time to work on the docs this week :)

**Comment by azerupi** [comment]
I will try to do some too :)
