### ISSUE TITLE
Usages of the <base> tag causes confusion

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang-nursery/mdBook#279]
Thought I'd document a painpoint we encountered: https://github.com/rust-lang/rust/pull/41476#issuecomment-301717315

**Comment by frewsxcv** [comment]
Anyone have opinions about removing `<base>`? Is that a lot of work?

**Comment by azerupi** [comment]
So `<base>` is in place to always make internal links start from the root. In my opinion this is easier to reason about and less prone to invalid links when you move around some chapters.

I am not opposed to remove it, but then maybe we would need to process internal links during the build phase to make them start from the root?

**Comment by AndyGauge** [comment]
At Rust Cookbook, while trying to implement link checkers in the CI, we were hard pressed to find one that accepted `<base href="../">`.  Both html-proofer and w3 validators fail to process the links.  

https://validator.w3.org/checklink?uri=https%3A%2F%2Fdoc.rust-lang.org%2Fstable%2Frust-by-example%2Fhello%2Fprint.html&hide_type=all&depth=&check=Check demonstrates some of the output we were seeing.  Currently, @budziq is writing a link checker that accepts base href='../' as valid, but it is my thinking that if w3 validators are failing, it might be malformed.

**Comment by Michael-F-Bryan** [comment]
I believe this should be resolved by #603. We're planning to migrate away from the `base` tag and instead all links will be relative to their parent directory.

**Comment by AndyGauge** [comment]
@Michael-F-Bryan I was planning on testing #603 against the cookbook this weekend but ran into all kinds of technical issues.  I suspected it would resolve my issues, and I'm thankful you clarified that for me.

**Comment by badboy** [comment]
This is now fixed by #603 and should be closed.
