### ISSUE TITLE
Support the missing features for Rust By Example

### ISSUE THREAD

**Issue by azerupi** [rust-lang-nursery/mdBook#308]
This issue serves to track the remaining issues before [RBE](https://github.com/rust-lang/rust-by-example) can be ported over to mdBook.

### Blockers
- [x] #247 - Editable code snippets (through [ACE](https://ace.c9.io/)?)
- [x] Test code snippets (maybe the existing test command is sufficient, but probably not)

### Nice to have
- [ ] Check for dead links
- [x] Good error message when a file to include is not present

If I missed anything or there are other requirements that need to be added, feel free to post them below. I will update this post. 

\cc @mdinger @projektir @steveklabnik

**Comment by steveklabnik** [comment]
>  Test code snippets (maybe the existing test command is sufficient, but probably not)

I have a feeling that it is, personally.

The requirements look good to me 👍

**Comment by projektir** [comment]
> Test code snippets (maybe the existing test command is sufficient, but probably not)

I've tried out `mdbook test` and it seems to be working fine for code blocks.

**Comment by projektir** [comment]
I've made two issues for the nice to haves and plan to work on them unless anyone objects. I think they're straightforward enough to implement, useful for mdBook in general, and worth doing to make @mdinger's life easier. :smile:

**Comment by azerupi** [comment]
>the ACE link points back to this issue

Oh yes, my bad! I forgot the link 😊 

>I've made two issues for the nice to haves and plan to work on them unless anyone objects.

I am certainly not going to object 😉

**Comment by ehuss** [comment]
RBE has migrated, so I'm going to close this. The last issue seems to be covered by #356.
