### ISSUE TITLE
update the documentation for 0.1.0 release

### ISSUE THREAD

**Issue by budziq** [rust-lang-nursery/mdBook#368]
we have to document all the new features and options in config
as well as non backwards compatible behaviour.
- [x] clipboard support
- [x] optional MathJax
- [x] additional js
- [x] additional css
- [ ] ~~new theme (ayu)?~~
- [x] Document the version pinning for CI in the README
- [x] Document the `{{# include }}`
- [x] the `-L` option
- [x] editable playpens with ACE
- [x] Update contributor list (or remove it?)
- [ ] ...

**Comment by azerupi** [comment]
- [ ] Document the version pinning for CI in the README

**Comment by azerupi** [comment]
I just noticed that "copy to clipboard" is only available for Rust snippets. I would make it available on any code snippet. I am documenting it like that and we should fix it before the 0.1 release :)

**Comment by budziq** [comment]
agreed. I've created an issue for it
https://github.com/azerupi/mdBook/issues/432

**Comment by azerupi** [comment]
Thanks :)
I am going through the whole user guide updating where we need. I think I might be able to finish the documentation tonight. If I still have sometime left I will do the clipboard issue too. After that we should be good for a 0.1 release! :tada:

**Comment by azerupi** [comment]
I can't get the Ace editor to work now, so I can't document it. I checked what I already covered in the documentation. I will push what I have to a branch. I will continue later.

**Comment by budziq** [comment]
Awesome! 
> I can't get the Ace editor to work now, so I can't document it.

I've stumbled on it just today when bumping mdbook version for rust-cookbook. 
You need to enable it both in book.toml and annotate each snippet with `rust,editable` for it to work but I've decided against enabling for now as ACE goes wonky with `#` hidden lines.

**Comment by azerupi** [comment]
Oh I got it to work now!
I think it was a problem with enabling it while I used `mdbook serve`. Stopping the serve, running build and running serve again fixed it. :)

But it's late, I will continue another day 😉

**Comment by Michael-F-Bryan** [comment]
The configuration system has slightly changed ([see #457](https://github.com/rust-lang-nursery/mdBook/pull/457#issuecomment-343725475)) so that's another reason to put out `0.1` as the next release. I added a temporary compatibility thing which will still let you load the previous config file version, emitting a warning and migration instructions in the process.

I didn't know you could use the ACE editor to edit snippets. I'll check it out in the coming days and see if I can help document it.

**Comment by projektir** [comment]
Editable playpens/ACE have been documented (ish): #552.

**Comment by mattico** [comment]
The docs could still use some love, but I think this issue has been covered.
