### ISSUE TITLE
Buttons sometimes overlap code

### ISSUE THREAD

**Issue by azerupi** [rust-lang-nursery/mdBook#389]
![image](https://user-images.githubusercontent.com/7647338/28922612-2fe62544-785b-11e7-9fe4-d8cdb0d3561b.png)

In the image above, a long comment on the first line interferes with the button who are rendered on top. This makes the comment hard / impossible to read, but also the buttons less visible. I am not sure yet how we should fix this. 

My first idea would be to add a background to the buttons so that even if text is placed underneath it is hidden by a uniform background. However this would only be a partial fix because the code underneath would be impossible to read.

**Comment by budziq** [comment]
Somewhat related https://github.com/rust-lang-nursery/rust-cookbook/issues/263

I was thinking about making the buttons more prominent. Hmm possibly blink on playpen hover. Maybe I should create a separate issue about buttons not being discoverable.

**Comment by ehuss** [comment]
I believe this has been fixed since #338.
