### ISSUE TITLE
Improve output to stdout

### ISSUE THREAD

**Issue by azerupi** [rust-lang-nursery/mdBook#407]
Currently, rendering a book prints lines like these on the terminal:
```
INFO:mdbook::renderer::html_handlebars::hbs_renderer: [*] Creating "./introduction.html" ✓
INFO:mdbook::renderer::html_handlebars::hbs_renderer: [*] Creating index.html from "/Volumes/FilesOSX/Users/azerupi/Programming/Rust/mdBook/../../TESTS/timely-dataflow/mdbook/book/./introduction.html" ✓
INFO:mdbook::renderer::html_handlebars::hbs_renderer: [*] Creating "./chapter_0/chapter_0.html" ✓
INFO:mdbook::renderer::html_handlebars::hbs_renderer: [*] Creating "./chapter_0/chapter_0_1.html" ✓
INFO:mdbook::renderer::html_handlebars::hbs_renderer: [*] Creating "./chapter_0/chapter_0_2.html" ✓
INFO:mdbook::renderer::html_handlebars::hbs_renderer: [*] Creating "./chapter_0/chapter_0_3.html" ✓
INFO:mdbook::renderer::html_handlebars::hbs_renderer: [*] Creating "./chapter_1/chapter_1.html" ✓
INFO:mdbook::renderer::html_handlebars::hbs_renderer: [*] Creating "./chapter_1/chapter_1_1.html" ✓
INFO:mdbook::renderer::html_handlebars::hbs_renderer: [*] Creating "./chapter_1/chapter_1_2.html" ✓
INFO:mdbook::renderer::html_handlebars::hbs_renderer: [*] Creating "./chapter_1/chapter_1_3.html" ✓
INFO:mdbook::renderer::html_handlebars::hbs_renderer: [*] Creating "./chapter_2/chapter_2.html" ✓
INFO:mdbook::renderer::html_handlebars::hbs_renderer: [*] Creating "./chapter_2/chapter_2_1.html" ✓
INFO:mdbook::renderer::html_handlebars::hbs_renderer: [*] Creating "./chapter_2/chapter_2_2.html" ✓
INFO:mdbook::renderer::html_handlebars::hbs_renderer: [*] Creating "./chapter_2/chapter_2_3.html" ✓
INFO:mdbook::renderer::html_handlebars::hbs_renderer: [*] Creating "./chapter_2/chapter_2_4.html" ✓
INFO:mdbook::renderer::html_handlebars::hbs_renderer: [*] Creating "./chapter_3.html" ✓
INFO:mdbook::renderer::html_handlebars::hbs_renderer: [*] Creating "./chapter_3/chapter_3_1.html" ✓
INFO:mdbook::renderer::html_handlebars::hbs_renderer: [*] Creating "./chapter_3/chapter_3_2.html" ✓
INFO:mdbook::renderer::html_handlebars::hbs_renderer: [*] Creating "./chapter_3/chapter_3_3.html" ✓
INFO:mdbook::renderer::html_handlebars::hbs_renderer: [*] Creating "./chapter_5.html" ✓
INFO:mdbook::renderer::html_handlebars::hbs_renderer: [*] Creating "./chapter_5/chapter_5_1.html" ✓
INFO:mdbook::renderer::html_handlebars::hbs_renderer: [*] Creating "./chapter_5/chapter_5_2.html" ✓
INFO:mdbook::renderer::html_handlebars::hbs_renderer: [*] Creating "./chapter_5/chapter_5_3.html" ✓
INFO:mdbook::renderer::html_handlebars::hbs_renderer: [*] Creating "./chapter_5/chapter_5_4.html" ✓
INFO:mdbook::renderer::html_handlebars::hbs_renderer: [*] Creating "./chapter_4/chapter_4.html" ✓
INFO:mdbook::renderer::html_handlebars::hbs_renderer: [*] Creating "./chapter_4/chapter_4_1.html" ✓
INFO:mdbook::renderer::html_handlebars::hbs_renderer: [*] Creating "./chapter_4/chapter_4_2.html" ✓
INFO:mdbook::renderer::html_handlebars::hbs_renderer: [*] Creating print.html ✓
```

That is a lot of repetition and even information the user should not need to see. The `INFO:mdbook::renderer::html_handlebars::hbs_renderer:` should be hidden from stdout. Also, it may not be that interesting to list out all the files we create by default. We should probably hide this behind a verbose flag.

I think we need a better solution for logging and printing to the user. The two don't seem to mix well, we already considered doing like cargo and separate logging from user output. Having two separate mechanics for the two. Maybe it's time to reconsider something like that and improve our story dramatically here.

So as we brainstorm, here are a couple of things I would consider to be the **requirements**:

- **Output should be minimal** by default, stating if generation was successful or not. More information can be hidden behind a verbose flag `-v` and if needed even a double verbose flag `-vv`
- **The user should not see any of the internals** (function names, module hierarchy, ...) that is information that belongs in the logs. We could have a debug flag that enables the log output like `-d` or `-d log.txt` instead or in addition to the environment variable.
- If we rework the user output, I would like to see **coloured output** for terminals
- If we decouple the logging from the user output, we can (and should) use it more liberally in the code to make debugging user problems easier for us.

**Comment by boxdot** [comment]
Is this actually still relevant? I don't see the above output anymore:
```
2018-01-29 21:06:09 [INFO] (mdbook::book): Book building has started
2018-01-29 21:06:09 [INFO] (mdbook::book): Running the html backend
```
I guess, it still would make sense to output that the book was created successfully?

**Comment by Michael-F-Bryan** [comment]
Thanks @boxdot. We probably should have closed this issue when we toned down the logging in #569, although that was mostly a case of converting `info!()` log messages into `debug!()`. 

I'll look at adding a final "book built successfully" message after the renderers have run.
