### ISSUE TITLE
Tag for 0.0.22 is missing

### ISSUE THREAD

**Issue by RalfJung** [rust-lang-nursery/mdBook#420]
The git repo contains tags for most versions, but not for 0.0.22.

**Comment by azerupi** [comment]
@steveklabnik did the 0.0.22 release, but forgot to push a tag. I can't seem to find a commit indicating the release, I did narrow it down to may 19th or just before.

I'm not sure if crates.io/cargo offers a way to find the commit at which a release is made? Or maybe @steveklabnik can find the commit at which the 0.0.22 release was made?

**Comment by steveklabnik** [comment]
Gah! sorry about that :(

What we could do is, download the source, and then diff it against different commits, and see which one is the same :/

**Comment by azerupi** [comment]
Yeah, I am not particularly motivated to do so 😉 
@RalfJung is there a need for the 0.0.22 tag or was it just for consistency?

**Comment by RalfJung** [comment]
I had wanted to find out what changed when I prepared <https://github.com/rust-lang/rust/pull/44267>. But TBH, consistency seems enough of a reason. ;)

**Comment by Dylan-DPC** [comment]
Closing this as there's nothing we can do about it now
