### ISSUE TITLE
tests/testing.rs tests spuriously fail on latest nightly 

### ISSUE THREAD

**Issue by budziq** [rust-lang-nursery/mdBook#433]
Either `mdbook_can_correctly_test_a_passing_book` or `mdbook_detects_book_with_failing_tests` fails in latest nightly 

[appveyor nightly fail](https://ci.appveyor.com/project/azerupi/mdbook/build/job/2gn6q77kyps7w4dh)
[travis nightly fail](https://travis-ci.org/azerupi/mdBook/jobs/274377653)

**Comment by azerupi** [comment]
Hmmm another nightly regression?
I will look at the logs in more details later today.

**Comment by budziq** [comment]
looks like it's either problem with rustdoc or rustup.

calls to `rustdoc --test ./path/to/file.md` when run with nightly toolchain (`rustup default nightly` or `cargo +nightly`) will always fail:
- on linux silently without ever setting the error code (giving false possitives)
- on windows with "command failed: `rustdoc.exe`"

**Comment by steveklabnik** [comment]
Yes, this is a bug in nightly Rust; it will be fixed soon. Nothing to do
here really.

**Comment by azerupi** [comment]
Ok, thanks! :)

**Comment by Michael-F-Bryan** [comment]
I believe this is no longer an issue.
