### ISSUE TITLE
Add header.hbs

### ISSUE THREAD

**Issue by Havvy** [rust-lang-nursery/mdBook#453]
Both the second edition of The Rust Programming Language and The Rust Reference put up a warning at the top of each page. To do this, we currently have our own `theme/index.hbs`. While this works, it does sort of pin us to a specific release of mdbook. We can occasionally rebase against index.hbs, but that has to be remembered to be done and takes away time from working on other things.

It'd be nice if there was a `theme/header.hbs` that we could override instead. Then at least the Rust Reference wouldn't need to override `index.hbs`, and TRPL would have a lot smaller diff to rebase with.

**Comment by budziq** [comment]
Actually I was thinking about the exact same feature for some time to split the index.hbs into few sections with default implementation. Candidates for such extraction would probably be:
- sidebar
- button bar (this one actoulalby be required by "Rust Cookbook")
- header (needed by "The Rust Programming Language" and "The Rust Reference")
- footer

**Comment by steveklabnik** [comment]
The Cookbook also does this, but for othe things.

**Comment by Havvy** [comment]
This has been fixed. 😄
