### ISSUE TITLE
Render checklists

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/mdBook#473]
I would expect the following markdown to turn into a checklist, as it does on GitHub.

- [ ] A
- [ ] B

```md
- [ ] A
- [ ] B
```

Instead it turns into:

![73d8927b-7f27-4bb2-8fe5-66ef9ea4a006](https://user-images.githubusercontent.com/1940490/31868630-00d45a7a-b756-11e7-91f5-b58ad06c8ed1.png)

---

I use a checklist in https://serde.rs/derive.html from which it may be possible to port over the style.

**Comment by budziq** [comment]
Hi, 

Checklists are outside of the commonmark spec. There is a [request to add these as an extension in pulldown-cmark](https://github.com/google/pulldown-cmark/issues/28) but it has zero traction so far.

**Comment by ehuss** [comment]
Task lists are now supported in pulldown-cmark.  This is blocked on #898.

**Comment by plul** [comment]
#898 was merged. This can be closed.

**Comment by ehuss** [comment]
Thanks!
