### ISSUE TITLE
[Usability] Changing Chapter removes focus from main area

### ISSUE THREAD

**Issue by StefanSchoof** [rust-lang-nursery/mdBook#480]
I read the [Rust Book online](https://doc.rust-lang.org/book/second-edition/) on a Desktop Firefox. Using the arrow key to scroll down and up while reading. After the end of a chapter I press the left arrow and get to the next chapter. But now the main windows has lost the focus and I have to click in the man area to get scrolling with arrow down and up again.

**Comment by sorin-davidoi** [comment]
@StefanSchoof is this still an issue? I can't replicate it on master.

**Comment by StefanSchoof** [comment]
This is not an issue any longer.
