### ISSUE TITLE
Why are there no recent builds for windows?

### ISSUE THREAD

**Issue by baxebu** [rust-lang-nursery/mdBook#481]
Hello! Why are there no recent builds for windows? The latest version is build a long time Mar 11 2017? Why are you ignoring Windows?

**Comment by steveklabnik** [comment]
I use mdbook on Windows daily, though I don't use the binary builds.

I'm sure something just went wrong in the deploy process.

**Comment by baxebu** [comment]
Can you add the latest builds for windows? I always want to see the latest builds in releases?

**Comment by ehuss** [comment]
Windows builds are working again in the latest release: https://github.com/rust-lang-nursery/mdBook/releases/tag/v0.3.0
