### ISSUE TITLE
The documentation linked to on your crates.io site and readme both produce a 404.

### ISSUE THREAD

**Issue by Alfriadox** [rust-lang-nursery/mdBook#487]
I suggest changing the links to [https://docs.rs/mdbook/0.0.26/mdbook/]( https://docs.rs/mdbook/0.0.26/mdbook/) or something that's at least functional.

**Comment by Michael-F-Bryan** [comment]
Looks like this comes under the umbrella of #485.

**Comment by Alfriadox** [comment]
@Michael-F-Bryan I think you're right.
