### ISSUE TITLE
Travis builds failing for OSX & beta

### ISSUE THREAD

**Issue by Michael-F-Bryan** [rust-lang-nursery/mdBook#490]
For some reason we're encountering a permissions error when running the OSX/beta travis build. An [example] is trying to merge #465 or #422.

This is the error message:

![screenshot_2017-11-16_150757](https://user-images.githubusercontent.com/17380079/32878216-10054bd8-cae0-11e7-864d-c77597c8c49a.png)

@budziq or @steveklabnik, have you got any idea what may be causing this?

[example]: https://travis-ci.org/rust-lang-nursery/mdBook/builds/301638661

**Comment by budziq** [comment]
@Michael-F-Bryan on first glance it looks like https://github.com/rust-lang/cargo/issues/4699

**Comment by Michael-F-Bryan** [comment]
I added a couple debug commands to see what's going on in that directory and that seems to be the issue.

![screenshot_2017-11-19_000033](https://user-images.githubusercontent.com/17380079/32982271-ce8cad3e-ccbc-11e7-9a08-f0ba14571ba7.png)

I'm thinking the easiest solution is to temporarily remove the OSX job until rust-lang/cargo#4699 is solved. @budziq, can you think of any other workaround?

**Comment by budziq** [comment]
We can either disable osx (or just beta) temporarily or just wait doing nothing untill cargo gets fixed. I'd probably just disable the beta for now as the least valuable check.

**Comment by Michael-F-Bryan** [comment]
I think I'll disable `beta` because you tend to only ever use `stable` or `nightly`.

**Comment by budziq** [comment]
Looking at the 1.22.1 release notes, the problem with cargo on MacOS beta should be fixed.

**Comment by sorin-davidoi** [comment]
@Michael-F-Bryan I guess this can be closed?

**Comment by Michael-F-Bryan** [comment]
Yep.
