### ISSUE TITLE
Warn if a book.json exists

### ISSUE THREAD

**Issue by torkleyy** [rust-lang-nursery/mdBook#509]
I think that `book.json` was previously accepted, but it seems that now only TOML files are allowed. While I prefer TOML over JSON for config files, it wasn't easy to find out it's been changed.

Should such a warning be added to `MDBook` or should it go into the command-line tool only?

**Comment by Michael-F-Bryan** [comment]
Thanks for pointing this out, when updating the configuration we added a compatibility shim for people using the legacy `book.toml` format but it looks like we forgot to mention the JSON format is no longer used.

 I think the easiest way to deal with this would be to check whether a `book.json` exists while loading the book (probably somewhere around [here]) and if it exists we emit a warning saying the JSON format is no longer used. How does that sound?

[here]: https://github.com/rust-lang-nursery/mdBook/blob/d69bc9c7c3b770f2e603617097fb1a367b2e6069/src/book/mod.rs#L66-L80
