### ISSUE TITLE
Poor Error Message for Missing Addition CSS File

### ISSUE THREAD

**Issue by Havvy** [rust-lang-nursery/mdBook#512]
When you add an additional css file to the project, but that file doesn't exist in the filesystem, mdbook unhelpfully prints out:

```
An error occured:
No such file or directory (os error 2)
```

It should specify which file doesn't exist and that it's looking for it because it's specified in the config file.

**Comment by Michael-F-Bryan** [comment]
Wow, that's a really poor error message! Hopefully #513 fixes the issue.

Before:

```
...
Error: Rendering failed
Caused by: No such file or directory (os error 2)
```

After:

```
...
Error: Unable to copy across additional CSS and JS
Caused by: Copying asd.css failed
Caused by: No such file or directory (os error 2)
```
