### ISSUE TITLE
Can't install mdbook

### ISSUE THREAD

**Issue by ritiek** [rust-lang-nursery/mdBook#531]
Hi there!

I can't seem to install mdbook. It always errors out at `proc_macro` crate:

```
$ cargo install mdbook
```

```
   ....
   Compiling serde_derive v1.0.27
   Compiling handlebars v0.29.1
error[E0463]: can't find crate for `proc_macro`
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-1.0.27/src/lib.rs:37:1
   |
37 | extern crate proc_macro;
   | ^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

error: Could not compile `serde_derive`.
warning: build failed, waiting for other jobs to finish...
```

It ends up with the the same error even when installing from git:

```
$ cargo install --git https://github.com/rust-lang-nursery/mdBook.git
```

Any ideas?

**Comment by Michael-F-Bryan** [comment]
What version of `rustc` are you using? I believe the `proc_macro` crate was introduced around `1.15` when custom derives were established, whereas stable is currently at `1.23.0`.

**Comment by ritiek** [comment]
Yep, that was it. I had my rustc defaults set to a custom build (`rustc 1.24.0-dev`). Switched back to `rustc 1.21.0` and now it builds successfully. Thank you. I wonder what happened with `proc_macro` in non-released rustc builds?

**Comment by Michael-F-Bryan** [comment]
That's really odd. You'd assume CI would pick up if there were any issues with the `proc_macro` crate, seeing as it's a big part of custom derives and have been stable for ages. 

I'd see if you can install `mdbook` after recompiling `rustc` against the latest `master`. It may just be something funny with your custom build.

**Comment by ritiek** [comment]
I guess so. I'll try building `rustc` from `master` again and let you know how it goes.

**Comment by ritiek** [comment]
Yep, I probably messed up something with my `rustc` build. `mdbook` builds fine with rust-lang/rust@2148bcd5fa508d44c2c3517dccf8450a5984e315.
