### ISSUE TITLE
"color: #6e6b5e;" makes some links invisible

### ISSUE THREAD

**Issue by xftroxgpx** [rust-lang-nursery/mdBook#537]
**EDIT:** for updated info jump to [this](https://github.com/rust-lang-nursery/mdBook/issues/537#issuecomment-433096992) comment.

_Old info(which still applies to the second edition book) follows:_

This line
https://github.com/rust-lang-nursery/mdBook/blob/e825357848d7641e10abbd9ca4bff0ff17cc73c6/src/theme/book.css#L387
or more specifically (thanks to [contributing](https://github.com/rust-lang-nursery/mdBook/blob/master/CONTRIBUTING.md#making-changes-to-the-style)), this stylus source line:
https://github.com/rust-lang-nursery/mdBook/blob/e825357848d7641e10abbd9ca4bff0ff17cc73c6/src/theme/stylus/themes/base.styl#L111

causes the behavior seen in the screenshots here: https://github.com/rust-lang/book/issues/1115
ie. links for text inside `backticks` are not visible(ie. blue), unless you mouse over them then they become just underlined.

in context:
```css
    /* Inline code */
    :not(pre) > .hljs {
        display: inline-block;
        vertical-align: middle;
        padding: 0.1em 0.3em;
        border-radius: 3px;
        color: $inline-code-color;
    }
```

**Comment by xftroxgpx** [comment]
I'm personally using this workaround locally, but I couldn't recommend this for a PR for I don't understand its implications currently (ie. it may appear to work just fine for this case, but it might have some other unintended side-effects that I've yet to encounter; besides I don't really understand what it's used for, really):

```patch
diff --git a/src/theme/book.css b/src/theme/book.css
index 7e83864bc..c082c5a4b 100644
--- a/src/theme/book.css
+++ b/src/theme/book.css
@@ -380,7 +380,7 @@ table thead td {
   vertical-align: middle;
   padding: 0.1em 0.3em;
   border-radius: 3px;
-  color: #6e6b5e;
+/*  color: #6e6b5e; unhide normally blue links inside backticks, see https://github.com/rust-lang/book/issues/1115 */
 }
 .light a:hover > .hljs {
   text-decoration: underline;
diff --git a/src/theme/stylus/themes/base.styl b/src/theme/stylus/themes/base.styl
index 7bc8d7131..935e1f0f6 100644
--- a/src/theme/stylus/themes/base.styl
+++ b/src/theme/stylus/themes/base.styl
@@ -106,7 +106,7 @@
         vertical-align: middle;
         padding: 0.1em 0.3em;
         border-radius: 3px;
-        color: $inline-code-color;
+        /* color: $inline-code-color; commented out to avoid https://github.com/rust-lang-nursery/mdBook/issues/537 or https://github.com/rust-lang/book/issues/1115 */
     }
 
     a:hover > .hljs {
```

**Comment by Michael-F-Bryan** [comment]
I've noticed this issue in the past and it's kinda bugged me. It seems like we've got an issue where two rules apply to links within code snippets, (the usual blue colour for links, and the `$inline-code-color` for code snippets) and the second one wins because it's last and more specific. 

I think it's still important that we apply the `$inline-code-color` to text within backticks, so to fix the issue we could add a rule directly afterwards which resets the colour for links back to its default.

i.e. something like this:

```stylus
:not(pre) > .hljs {
    display: inline-block;
    vertical-align: middle;
    padding: 0.1em 0.3em;
    border-radius: 3px;
    color: $inline-code-color;
}

:not(pre) > .hljs a {
  color: $default-link-color;
}
```

My CSS is a little rusty though, so it's probably a good idea to get a second opinion.

**Comment by xftroxgpx** [comment]
```css
:not(pre) > .hljs a {
  color: $default-link-color;
}
```
Tried that but is seems to have no effect.

Meanwhile, some changes happened on master and I'm happy to report that the "Result" part from the title is no longer blue(as it [was](https://user-images.githubusercontent.com/26243389/34873135-3a529c2a-f794-11e7-9826-ad7fa6b47c9b.png)) while using my patch from [above](https://github.com/rust-lang-nursery/mdBook/issues/537#issuecomment-357406272), as seen in this screenshot:
![screenshot_2018-01-20_22-17-51](https://user-images.githubusercontent.com/26243389/35188098-07d2c390-fe30-11e7-9086-b74efee59812.png)

**Comment by xftroxgpx** [comment]
Someone solved it here: https://rust-lang-nursery.github.io/rust-cookbook/basics.html#read-lines-of-strings-from-a-file
by having (at least):
```css
.light a > .hljs {
  color: #4183c4;
}
```
in their [custom.css](https://rust-lang-nursery.github.io/rust-cookbook/theme/custom.css)

**Comment by xftroxgpx** [comment]
Even though the OP still applies to [the currently live rust book second edition](https://doc.rust-lang.org/book/second-edition/ch02-00-guessing-game-tutorial.html#handling-potential-failure-with-the-result-type) because they must be using some old version of mdBook, [the current mdBook](33add4b5327d67819285b0364a14b9603ac66331) file structure changed so much that the OP doesn't apply to it anymore. 

I've rebuilt rust book second edition locally using this latest mdBook and ... looks like the file is now [`src/theme/css/chrome.css`](https://github.com/rust-lang-nursery/mdBook/blob/33add4b5327d67819285b0364a14b9603ac66331/src/theme/css/chrome.css#L178-L184) (instead of `src/theme/book.css`, see OP)
```
$ mdbook --version -v
mdBook v0.2.3-alpha.0
```

How the page looks normally(no changes from me):

![beforescreenshot_2018-10-25_17-15-56](https://user-images.githubusercontent.com/26243389/47511152-e2a66c00-d879-11e8-8081-ccaded1bcde2.png)

How the page looks after I untick that `color` (ie. how I wish it looked):
![afterscreenshot_2018-10-25_17-16-05](https://user-images.githubusercontent.com/26243389/47511159-e6d28980-d879-11e8-8eb2-f4007c238307.png)

Link to the code that's seen in the screenshot:
https://github.com/rust-lang-nursery/mdBook/blob/33add4b5327d67819285b0364a14b9603ac66331/src/theme/css/chrome.css#L178-L184

therefore the new workaround, for me, is:
```patch
diff --git a/src/theme/css/chrome.css b/src/theme/css/chrome.css
index 0ab168696..a2408c520 100644
--- a/src/theme/css/chrome.css
+++ b/src/theme/css/chrome.css
@@ -180,7 +180,7 @@ html:not(.sidebar-visible) #menu-bar:not(:hover).folded > #menu-bar-sticky-conta
     vertical-align: middle;
     padding: 0.1em 0.3em;
     border-radius: 3px;
-    color: var(--inline-code-color);
+/*    color: var(--inline-code-color); commented out to unhide normally blue links inside backticks, see https://github.com/rust-lang/book/issues/1115 */
 }
 
 a:hover > .hljs {
```
