### ISSUE TITLE
Sticky header?

### ISSUE THREAD

**Issue by sorin-davidoi** [rust-lang-nursery/mdBook#545]
I find it quite frustrating that when I finish reading a chapter and want to skip to another one, I have to scroll to the top to toggle the sidebar. What do you think of making the header auto-hide when scrolling down (to save vertical space) and revealing itself when scrolling up (so you don't have to scroll all the way to the top, which can be a lot on mobile devices)? [Example of this approach](https://osvaldas.info/examples/auto-hide-sticky-header/).

**Comment by Michael-F-Bryan** [comment]
I know #474 introduced swipe gestures to hide/show the menu on mobile devices, but that's not overly discoverable unless you accidentally do it out of habit...

I think making the top `menu-bar` sticky would be a good idea, how about we make a prototype/trial and see how it looks?
