### ISSUE TITLE
Remove store.js

### ISSUE THREAD

**Issue by sorin-davidoi** [rust-lang-nursery/mdBook#548]
It is 17.25 KB, only used in three places, and we can just use `localStorage` instead (wrapped in a `try/catch` for safety). Should help to address #475.

**Comment by Michael-F-Bryan** [comment]
If it's only used in a couple places and (standardized) native APIs exist, we may as well use those instead of pulling in `store.js`. How hard would it be to remove?

**Comment by sorin-davidoi** [comment]
At a quick glance, it should be easy. I'll send a pull request later today.

**Comment by steveklabnik** [comment]
We brought in `store.js` to fix compatibility bugs. Are the versions that it fixes not browsers that we care about anymore?

**Comment by sorin-davidoi** [comment]
`localStorage` is [widely supported](https://caniuse.com/#feat=namevalue-storage) (most listed bugs are in IE). The discussion in #538  seems to indicate that we should follow [RFC 1985](https://github.com/rust-lang/rfcs/blob/master/text/1985-tiered-browser-support.md#supported-browsers), so I guess we don't need it anymore?

**Comment by steveklabnik** [comment]
Okay, so let's go back and look at the PR where it was added: https://github.com/rust-lang-nursery/mdBook/pull/324

This fixes these bugs:

* https://github.com/rust-lang-nursery/mdBook/issues/317
* https://github.com/rust-lang-nursery/mdBook/issues/322

317 is about "mobile safari", no version named.

322 is about chrome 58; RFC policy is 63 and 62. Are we sure this bug doesn't exist in 62+?

I'm not saying that we shouldn't remove `store.js`, I'm saying that we should ensure that we don't regress.

**Comment by sorin-davidoi** [comment]
That's why I suggested wrapping the calls in a `try/catch` block - it will prevent the page from breaking and degrade gracefully (settings will not be saved). My point is that these edge cases happen so infrequently, that it is not worth fetching, parsing and keeping in memory a library so big as `store.js`.

**Comment by steveklabnik** [comment]
I'd argue that that's dropping support for those browsers.

But again, really, all we have to do is verify that things work on the browsers are in the RFC. If they do, then this whole discussion is moot.

**Comment by Michael-F-Bryan** [comment]
I'm still on the fence about this one. As @steveklabnik alluded to, we need to make sure this doesn't introduce undesirable regressions. 

I don't think it'd be wise to merge anything until we make sure things still work on Chrome version 62 and mobile safari. 

As a data point, I just opened up the user guide in incognito mode (Chrome 63.0.3239.132, Arch Linux) and everything seems fine. Themes work when you refresh or browse pages, and code collapsing behaves as normal.

**Comment by steveklabnik** [comment]
1. make it work
2. make it right
3. make it fast

Totally agree that removing this probably has a lot of benefit, but something that's quick and doesn't work is bad.
