### ISSUE TITLE
something recent broke RBE

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang-nursery/mdBook#553]
We [render rust by example with the latest mdbook](https://github.com/rust-lang/rust-by-example/blob/master/.travis.yml#L10), and today, something is messed up. Look at the code blocks here: https://rustbyexample.com/flow_control/match.html

They're dark black, and impossible to read.

I haven't dug into the details yet, but maybe someone else knows?

**Comment by Michael-F-Bryan** [comment]
We recently merged a couple CSS/JS changes, so it may be related to one of the recent PRs. Presumably #538 or #535. When you pull up the dev tools console does it mention any scripts or stylesheets returning a 404?

CC: @sorin-davidoi 

---

I don't think I can replicate the issue. The code blocks seem to render normally on my machine.

![screenshot_2018-01-18_235110](https://user-images.githubusercontent.com/17380079/35106917-8784b382-fcaa-11e7-9c0e-ad1c934fa868.png)

**Comment by sorin-davidoi** [comment]
Yes, just took a look too but I don't know what to look for. Can you post some screenshots of how it's supposed to look?

**Comment by sorin-davidoi** [comment]
Ah, they look like this in Firefox.

![image](https://user-images.githubusercontent.com/2109702/35107386-12335aae-fc71-11e7-8cd1-8d9af0107fdd.png)

**Comment by sorin-davidoi** [comment]
Found the issue:

```js
document.querySelector("[href='ayu-highlight.css']").setAttribute('disabled', true);
```

does not disable the stylesheet in Firefox, we need to do

```js
document.querySelector("[href='ayu-highlight.css']").disabled = true;
```

Will open a PR. Sorry about that.
