### ISSUE TITLE
`clean` option to delete built book

### ISSUE THREAD

**Issue by bmusin** [rust-lang-nursery/mdBook#560]
What about adding `clean` command that will delete folder with previously built book?
I you don't mind, I want to implement it.

**Comment by Michael-F-Bryan** [comment]
That sounds like a good idea! The [API docs] are online, but feel free to ask questions if you are wondering where to get started.

[API docs]: http://rust-lang-nursery.github.io/mdBook/mdbook/

**Comment by bmusin** [comment]
Thanks for feedback. Currently I have no much time, but will inform If I will start doing.

**Comment by bmusin** [comment]
@Michael-F-Bryan, I added clean command, but I don't know how to return Err from function.
It should be variant of mdbook::errors::Result, so using just "Err" doesn't compile
```
 return Err("message")
   |                        ^^^^^^ expected struct `mdbook::errors::Error`, found reference
```
I don't know struct that implements mdbook::errors::Error, so that I could pass it to Err

**Comment by Michael-F-Bryan** [comment]
> It should be variant of mdbook::errors::Result, so using just "Err" doesn't compile

The function is expecting to return a `Result<_, Error>` but a `Err("message")` is `Result<_, &str>` so you get a type error. If you make a PR we'll be able to review the code and discuss these sorts of issues. 

If you prepend the PR title with something like `WIP:` we'll know it's still a work in progress and not ready to be merged.
