### ISSUE TITLE
Themes are broken the first time a page is loaded

### ISSUE THREAD

**Issue by Michael-F-Bryan** [rust-lang-nursery/mdBook#573]
I noticed that on `master` when you open up a book you've previously visited it'll be rendered without any CSS styling. This fixes itself when you change the themes and will never show itself again for that domain. 

I've seen something similar in the past where we'd changed the theme name being stored in local storage (because of a typo it went from `light` to `"light"`, or vice versa). I believe the underlying issue is that when loading the theme we don't properly handle the case where the theme specified in local storage doesn't exist.

I noticed this when rendering *The Book* as part of my final checks before pushing the 0.1 release. Unfortunately it blocks the release because styling will be broken for every single person who visits *The Book* (or any other document generated by `mdbook`) for the first time after this release and has been there before. 

@sorin-davidoi we may need to have a look at #550, possibly reverting it if there isn't an easy fix.

**Comment by sorin-davidoi** [comment]
I can't seem to be able to replicate this.

**Comment by Michael-F-Bryan** [comment]
When we had this issue a while back it was something to do with how the `index.hbs` template was being rendered. Chances are we may have accidentally reverted that original fix when updating the templates, so me mentioning #550 was probably a red herring. 

We may want to insert a check in `book.js` to make sure local storage gives us a valid theme, even if there wasn't one before #550. That way we can fall back to the default theme if we try to load an invalid one for whatever reason.

**Comment by Michael-F-Bryan** [comment]
Fixed :tada:
