### ISSUE TITLE
Dynamic spaceing in menu

### ISSUE THREAD

**Issue by dns2utf8** [rust-lang-nursery/mdBook#594]
I noticed with the latest release the margins around the entries in the menu pretty much doubled.
While I can understand that for mobile devices with touch screen, this behavior is a bit cumbersome with a mouse and now I have to scroll to see the full index.

My first response would be: check the browser for touch and use less space when appropriate.
What do you think?

**Comment by sorin-davidoi** [comment]
Media queries have a [`pointer`](https://drafts.csswg.org/mediaqueries/#pointer) property, but it is defined in CSS4 and it is at risk of being dropped from the spec. [Firefox also doesn't support it](https://caniuse.com/#feat=css-media-interaction).

**Comment by dns2utf8** [comment]
Maybe a combination of the following could help? I have not tested it yet!

> @media (-moz-touch-enabled: 1), (pointer: coarse) {
>   /* Rules for touch screens */
> }

and

> @media (hover: hover) { 
>   /* Rules for mouse devices */
>}
