### ISSUE TITLE
PDF TOC Support?

### ISSUE THREAD

**Issue by HaoZeke** [rust-lang-nursery/mdBook#621]
Hi, I was wondering if there's any plan to support a TOC in the generated PDF file...

(pdf generated using the print icon on the webpage)

**Comment by Michael-F-Bryan** [comment]
I'm not sure. I believe the print view originally just concatenates all the chapters together into one document for convenience. 

Now that mdbook lets you create your own backends it's probably a good idea to create a PDF renderer so you'll get a proper print version of a document.

**Comment by HaoZeke** [comment]
Is the backend feature documented somewhere? I couldn't find it (though I only did a superficial search).

I'd like to implement pandoc as a banckend then for TOC pdfs..

**Comment by Michael-F-Bryan** [comment]
There's actually a [while chapter on it][1] in the user guide, as well as a fairly detailed example which goes through most of the available features. That should be more than enough to get you going, but let me know if there's anything I can help with!

[1]: https://rust-lang-nursery.github.io/mdBook/for_developers/backends.html

**Comment by HaoZeke** [comment]
Ah, sorry, my bad, it seems very well documented, I'll repopen if I run into any issues.. :)

**Comment by SteveBetter** [comment]
Hi, @HaoZeke Is there any processes? I think Table of Contents is needed too.

**Comment by willscripted** [comment]
Add a self-referencing link to your summary doc to include it as a chapter in the book. It will be printed along with the other chapters.

```
- [Table of Contents](./SUMMARY.md)

# Section

- [Alpha](./alpha.md)
- [Bravo](./bravo.md)
- [Charlie](./charlie.md)
```

This will add the summary doc as a chapter that prints with the rest of the pdf.

Badboy's [mdbook-toc](https://github.com/badboy/mdbook-toc) plugin is also quite nice if you are looking for per-chapter table of contents.
