### ISSUE TITLE
Theme selector not working in some situations.

### ISSUE THREAD

**Issue by ehuss** [rust-lang-nursery/mdBook#628]
Changing themes doesn't seem to work in some situations.  Clicking on a theme in the theme selector just closes the selector without switching.

It seems to fail for me on Firefox 58.0.2 on Mac OS (oddly, it seems to work on Windows).  Also, Safari on iOS 10.3.3 seems to also exhibit the problem.

Checking in the debugger, it looks like in the `focusout` event handler, the `relatedTarget` is null (thus closing the selector and preventing the click handler from firing).  I tried investigating when that may be null, but I couldn't find a good explanation.

This seems to have been introduced in #611.

**Comment by sorin-davidoi** [comment]
I'll take a look at this tomorrow. According to [the documentation](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/relatedTarget), `relatedTarget` should always be defined for the `focusout` event.

**Comment by sorin-davidoi** [comment]
I can't reproduce this. `relatedTarget` should only be `null` if the focus is moved outside the document (in which case one certainly hasn't clicked any of the themes).

@ehuss if you are able to run this locally, can you give [this branch](https://github.com/sorin-davidoi/mdBook/tree/misc) a try? I replaced `focusout` with `blur` (with `capture: true`), which is equivalent but maybe works around whatever issue you are encountering.

**Comment by ehuss** [comment]
Switching to `blur` doesn't seem to help.  I'm guessing the issue is that in some browsers, buttons do not take focus when clicked on.  It works with keyboard navigation where the button has a distinct outline when focused.

Is there some reason the old method of having a click handler on the document doesn't work?

BTW, I noticed this also happens in desktop Safari 11.0.3 on macOS.

**Comment by sorin-davidoi** [comment]
> Is there some reason the old method of having a click handler on the document doesn't work?

Yes, the popup would not close when the focus leaves it.

I'll do more testing in Safari tomorrow.

**Comment by sorin-davidoi** [comment]
Alright, managed to reproduced it:
 - In Safari, when clicking on a theme or when using the Tab/Arrow keys to move focus between themes - in both cases `e.relatedTarget` is `null`
 - In Firefox on macOS, but only when clicking on a theme (moving focus using the keyboard works) - again, `e.relatedTarget` is `null`.

I'm confused to say the least - is this an underlying bug affecting macOS (and iOS)? Otherwise it couldn't affect Gecko (Firefox's engine).

Anyway, I've made [a branch](https://github.com/sorin-davidoi/mdBook/tree/fix-focusout-mac) to work around this. @ehuss Could you give it a shot?

**Comment by ehuss** [comment]
That seems to work better, although on Mobile Safari, tapping in the document doesn't dismiss the theme selector. You have to tap the theme selector icon to dismiss it.  I suspect it is due to [this explanation](https://www.quirksmode.org/blog/archives/2014/02/mouse_event_bub.html) of click bubbling.  The CSS trick with `cursor: pointer` works, but seems like a bad hack.  Personally, I think it's fine to just click the icon.
