### ISSUE TITLE
integrate pulldown-cmark 0.1.2, remove FIXME in summary.rs

### ISSUE THREAD

**Issue by seanjensengrey** [rust-lang-nursery/mdBook#633]
[pulldown-cmark](https://crates.io/crates/pulldown-cmark) is now at version `0.1.2` which satisfies the condition for removing the FIXMEs in `src/book/summary.rs`

[Issue 120](https://github.com/google/pulldown-cmark/issues/120) has been closed in pulldown-cmark with the release of 0.1.2.

* https://github.com/rust-lang-nursery/mdBook/blob/master/src/book/summary.rs#L316
* https://github.com/rust-lang-nursery/mdBook/blob/master/src/book/summary.rs#L325
* https://github.com/rust-lang-nursery/mdBook/blob/master/src/book/summary.rs#L487
* https://github.com/rust-lang-nursery/mdBook/blob/master/src/book/summary.rs#L513

**Comment by pduzinki** [comment]
May I work on this issue?

**Comment by seanjensengrey** [comment]
Maybe @Michael-F-Bryan could offer some guidance, I just noticed the new release of pulldown-cmark.

**Comment by mattico** [comment]
@pduzinki go right ahead. Feel free to ping me if you have any problems.

**Comment by Michael-F-Bryan** [comment]
> May I work on this issue?

Yep! Sorry for not replying, I've been a little busy lately and must have missed the notification.

The changes should be pretty straightforward. It's just a case of searching for any `FIXME` comments and swapping in the replacement code. Let me know if there are any issues.
