### ISSUE TITLE
can't find chapter/section preface on github.io

### ISSUE THREAD

**Issue by huangjj27** [rust-lang-nursery/mdBook#635]
When I `mdbook build` or `mdbook serve` locally, I can jump to the chapter preface using relative URLs like `chapter-A/_chapter.html`:
![can access the URL](https://user-images.githubusercontent.com/8068443/36943077-8ebd49ee-1fbd-11e8-8af2-112236b1c1e2.png)

However, when I deploy it to github.io, the relative URLs break:
![can't access the URL](https://user-images.githubusercontent.com/8068443/36943100-cb62c5d6-1fbd-11e8-9451-cb5ef84aa5fc.png)

I'm using `v0.1.3`. What's the cause?

**Comment by Michael-F-Bryan** [comment]
That's really weird! Looking at your `gh-pages` branch [you can see][1] the `task-model/_chapter.html` file, so `mdbook` is definitely rendering the chapter and putting it in the right spot. Could it be that GitHub Pages treats files starting with an underscore differently?

[1]: https://github.com/huangjj27/apr_zh-cn/blob/gh-pages/task-model/_chapter.html

**Comment by Michael-F-Bryan** [comment]
It looks like this behaviour is actually specific to GitHub Pages. They've designed it to work with jekyll out of the box, so anything starting with a leading underscore doesn't get served up.

As I mentioned on aturon/apr#1:

> **Edit:** Apparently it's [a GitHub Pages thing][1] and not mdbook-related. I usually call my chapter-level files `whatever/index.md` so then it's served up at either `whatever/` or `whatever/index.html` by your web server, hence why I never noticed this behaviour before.

I'm going to close this issue seeing as this is related to the naming convention people use and there's nothing mdbook can really do to fix it.

[1]: https://help.github.com/articles/files-that-start-with-an-underscore-are-missing/
