### ISSUE TITLE
Requests to play.rust-lang.org/meta/crates

### ISSUE THREAD

**Issue by anderejd** [rust-lang-nursery/mdBook#640]
There seems to be requests to https://play.rust-lang.org/meta/crates for every page load. Is this expected? I would like to turn that off somehow. Is this a bug? I'm not using mdbook for anything rust related.

**Comment by sorin-davidoi** [comment]
It's expected, but not ideal. We should refactor to only make the request if the page contains Rust code snippets that can be executed. There was a discussion in some other issue about it.

**Comment by anderejd** [comment]
Sounds good that it's on the radar for fixing. I feel a bit bad for rust-lang.org, my unrelated documentation project is kind of hammering it for every edit I make :)

**Comment by Michael-F-Bryan** [comment]
@sorin-davidoi, do you know what the request is needed for?

**Comment by sorin-davidoi** [comment]
I think it fetches some kind of metadata so that it can later run the Rust snippets.
