### ISSUE TITLE
Search results drawn on top of the page content

### ISSUE THREAD

**Issue by Michael-F-Bryan** [rust-lang-nursery/mdBook#643]
I think a recent update to CSS (presumably #638) changed how the search results are placed. If you do a search on the [User Guide] you'll see the search results being rendered directly on top of the page contents. 

I'm assuming this issue crept in because I'd looked at #638 locally in the past, but then merged #604 without checking to make sure #638 was still okay.
 
![image](https://user-images.githubusercontent.com/17380079/37447115-8d7520a6-285b-11e8-8654-89a65a6d0fea.png)

I'm not a CSS expert, but I *believe* the issue is because the search results (`id=searchresults-outer`) is `display: block`, while the page contents (`id=content`) is positioned using absolute coordinates. If you close the sidebar, the page gets rendered just fine again.

CC: @GuillaumeGomez, @mattico 

---

We're lucky I noticed this before making a big announcement on Reddit. Looking at the crates.io stats, it seems like only 65 people have downloaded `v0.1.4` so far, two of which are from me.

[User Guide]: https://rust-lang-nursery.github.io/mdBook/?search=command

**Comment by GuillaumeGomez** [comment]
I'll take a look.
