### ISSUE TITLE
Pressing 's' while in an editable code block opens the search instead of inserting the 's' characterr

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang-nursery/mdBook#654]
1. go to https://rustbyexample.com/hello/print.html
1. focus the editable text area
1. press 's'
1. notice the search opens instead of inserting the character 's'

reported in https://github.com/rust-lang/rust-by-example/issues/1040

**Comment by AntonLee** [comment]
Addressed in pr #653

**Comment by azerupi** [comment]
The PR has been merged. I'm closing this issue, feel free to re-open if it hasn't been solved.

**Comment by Lonami** [comment]
I was trying https://doc.rust-lang.org/nightly/rust-by-example/hello.html just now and the issue seems to still be there. Maybe it just hasn't rolled out to the website yet?

**Comment by azerupi** [comment]
No it is currently in master, not yet released to crates.io
The Rust book is using a pinned version of mdBook (if I am not mistaken) and updates it relatively quickly when we release a new version. So we need to at least wait for a new mdBook release.

**Comment by Lonami** [comment]
Okay, thank you :)
