### ISSUE TITLE
Still have run buttons when only using `#include`, not `#playpen`

### ISSUE THREAD

**Issue by shepmaster** [rust-lang-nursery/mdBook#675]
[The user guide states](https://rust-lang-nursery.github.io/mdBook/format/mdbook.html#inserting-runnable-rust-files):

> Inserting runnable Rust files
> With the following syntax, you can insert runnable Rust files into your book:
> 
> ```
> {{#playpen file.rs}}
> ```

But when I only use `#include`:

````
```rust
{{#include file.rs}}
```
````

I still get run buttons

![image](https://user-images.githubusercontent.com/174509/39100424-55c61bfe-4658-11e8-95cb-e1dc754f2fe9.png)

**Comment by Michael-F-Bryan** [comment]
I would have expected this to happen. You're getting run buttons because you've got code inside a `rust` code block, so it's actually not related to `{{#include ...}}`.

**Comment by shepmaster** [comment]
> because you've got code inside a rust code block

Could you point me to where it's documented that ` ```rust ` implies "run button"?

**Comment by shepmaster** [comment]
Perhaps a different way of asking this: What is the purpose of the `{{#playpen file.rs}}` syntax if it's not needed to trigger the run buttons?

**Comment by steveklabnik** [comment]
That's a good question. I'm not sure; I never use it.
