### ISSUE TITLE
Include a file that includes a file renders the handlebars

### ISSUE THREAD

**Issue by AndyGauge** [rust-lang-nursery/mdBook#678]
So I wanted to build rust Cookbook's table of contents dynamically.  I was creating each chapter's table and then including each of those chapter's tables into a master table.

Each chapter includes the relevant badges for crates (which are images) and category links.  In fact most of the cookbook's pages have at the bottom {{#include links.md}}.  

When I render the master table, including each of the chapter tables, they a separated by a rendered {{#include links.md}}  I'm looking for an easy solution to either:

 1. Include this file from the included file
 2. remove the {{#include }} from the output with a preprocessor

The only solution I can think of is creating each of the chapter's tables without the include at the bottom, and include that in a file that has:

{{#include algorithms/algorithms.md}}
{{#include links.md}}

and doing:
{{#include algorithms/algorithms.md}} in the master table.  

The challenge is that will require an extra file for every chapter, just to include the master table, and I'm afraid the project will begin to look less like a book and more like a template.  

Before I move that direction, I wanted to make sure this wasn't just something I was doing wrong.  There's no errors output by mdbook in the rendering.  When I see {{#include link.md}} somewhere, I usually see an error in the cli saying the file wasn't found (to that effect).

**Comment by Michael-F-Bryan** [comment]
> So I wanted to build rust Cookbook's table of contents dynamically. I was creating each chapter's table and then including each of those chapter's tables into a master table.

I'm just throwing out ideas here, but what if created your own pre-processor which will scan the book and then dynamically insert a table of contents (e.g. replacing some custom `{{#cookbook-toc}}` string)? It's definitely more work, but there's [a pretty good guide][1] on writing pre-processors and this would give you full control over the entire book before it gets sent to the renderer. This sort of dynamic updating of documents is exactly the use case for pre-processors!

> The challenge is that will require an extra file for every chapter, just to include the master table, and I'm afraid the project will begin to look less like a book and more like a template.

That sounds like a massive pain in terms of maintenance as well. It means you've got to constantly keep your `links.md` file in sync with the rest of the document.

[1]: https://rust-lang-nursery.github.io/mdBook/for_developers/preprocessors.html

**Comment by AndyGauge** [comment]
Those are great thoughts.  I'm not willing to block on progress at this time.  I'd like to get the book into a 1.0 state quickly and then make it slick.

There's progress towards a visual overhaul that would take us away from mdBook, so I don't want to write a preprocessor until we know that vision.
