### ISSUE TITLE
Include Nix files

### ISSUE THREAD

**Issue by flosse** [rust-lang-nursery/mdBook#681]
I just tried to include a Nix file:
```md
Adjust the `/mnt/etc/nixos/configuration.nix` file for your needs.
An example configuration looks like this:

{{#include ../configuration.nix}}
```
And this gets rendered:

![screenshot-2018-4-27 installation -](https://user-images.githubusercontent.com/276043/39379502-baa8b02a-4a5b-11e8-8a8c-e6bf38bc8f4b.png)

How could I prevent the interpretation of the files content?

**Comment by mattico** [comment]
I'm not super knowledgable about how `{{#include}}` works, but I think you'd do it like this:

    ```nix
    {{#include ../configuration.nix}}
    ```

**Comment by flosse** [comment]
Indeed, that's almost obvious :)
It works and it might be cool to mention this in the guide (https://rust-lang-nursery.github.io/mdBook/format/mdbook.html#including-files)!?
