### ISSUE TITLE
Add support for localization

### ISSUE THREAD

**Issue by cauebs** [rust-lang-nursery/mdBook#687]
It would be great if we could provide multiple versions of a book and switch between them using a menu similar to the one we have for themes.

**Comment by cauebs** [comment]
Someone pointed out that this might be a duplicate of #5. I'm closing this one.

**Comment by Endermanbugzjfc** [comment]
> This should be fairly straightforward:
> 
> 1. Add a config option to set the default language.
> 2. Determine & document the folder structure used for the translations.
> 3. Change index generation to ignore translations.
> 4. Set the `lang` template parameter in `hbs_renderer` based on the page path + default config.
> 5. Add a menu to the html template + stylus.
> 6. In `hbs_renderer`, look for different versions of the current page and add them to the template parameter.
> 7. Set the [language](https://docs.rs/elasticlunr-rs/2.2.0/elasticlunr/lang/enum.Language.html) used to generate the search index.
> 8. Add a cargo feature to disable this functionality, since rustc can't have the search language support due to licensing issues.
> 
> Edit:
> 
> Links might also need to be adjusted so they point at the page for the current language. This might not be necessary if the correct relative links are used, I'd have to check.

Could anyone give me some instances, please?
