### ISSUE TITLE
Strikethrough?

### ISSUE THREAD

**Issue by crsaracco** [rust-lang-nursery/mdBook#700]
Does mdBook support markdown's  `~~strikethrough~~` (~~strikethrough~~)? Using v0.1.7, I can't seem to make it parse.

**Comment by mrec** [comment]
[There's an open ticket for it](https://github.com/raphlinus/pulldown-cmark/issues/27) from 2016, but there doesn't seem to be any activity on the project these days.

**Comment by Dylan-DPC** [comment]
The feature is now available in the pulldown-cmark

**Comment by ehuss** [comment]
I think the `ENABLE_STRIKETHROUGH` option will need to be added for this to work?  And I think it will need to wait for #898.
