### ISSUE TITLE
Editable code fragments use a font size too small to be easily readable

### ISSUE THREAD

**Issue by Eyenseo** [rust-lang-nursery/mdBook#705]
As per request on rust-lang/rust-by-example#1087 that flagged this as upstream issue.

On [rust-by-example](https://doc.rust-lang.org/stable/rust-by-example/hello.html) the editable code example has a very small font size (for me):
![foo](https://user-images.githubusercontent.com/3954885/41227833-808d9d2c-6d76-11e8-8fb9-60f3c5a777b7.jpg)
While [book/second-edition](https://doc.rust-lang.org/book/second-edition/ch01-02-hello-world.html#writing-and-running-a-rust-program) uses the same font size for text and code, which is preferable in my opinion.

**Comment by Eyenseo** [comment]
OK so I poked a little bit around and found the following: 
* This is only an issue if the editor is indeed editable - else ace won't be loaded. 
* The font size can be easily configured ```
editor.setOptions({
  fontSize: "10pt"
});```
* [This](https://github.com/rust-lang-nursery/mdBook/blob/f01bf88e69cf84fb253962f5d78b7c5a4eaf8306/src/theme/playpen_editor/editor.js#L8) is where it should be adjusted

I do not know enough of mdbook to make a pull request currently. For me setting the font size to `11pt` looks good but I'm unsure if that is the right font size for other people too. Does anyone have any idea if mdbook sets font sizes / what to query to get the correct one for the editors?

**Comment by mattico** [comment]
The font size for code is set here: https://github.com/rust-lang-nursery/mdBook/blob/2a55ff62f36245d384f9d270e403dfc395190f52/src/theme/stylus/general.styl#L14

I think it would be fine to hard code this value, perhaps with a comment in both location reminding others to change them both.

It would also be possible to use something like `window.getComputedStyle(document.querySelector("code")).fontSize`

**Comment by Eyenseo** [comment]
> `window.getComputedStyle(document.querySelector("code")).fontSize`

reports the wrong value for me.
