### ISSUE TITLE
Add instructions on how to run `mdbook` in Travis CI

### ISSUE THREAD

**Issue by fitzgen** [rust-lang-nursery/mdBook#714]
Both for testing and deploying to gh-pages.

I'm installing with `cargo install` right now, but compiles are killing my CI turnaround times. I see that tarballs exist in the releases tab on github, but it would be super awesome if there were instructions on how to download and use them from Travis CI. I doubt I'm the only person who would be interested in such instructions :)

**Comment by steveklabnik** [comment]
The book uses this idiom https://github.com/rust-lang/book/blob/master/.travis.yml#L16

Another project I have does this, which is better, IMHO https://github.com/intermezzOS/book/blob/master/.travis.yml#L12-L14 combined with https://github.com/intermezzOS/book/blob/master/.travis.yml#L5-L6 it keeps this time down; see https://travis-ci.org/intermezzOS/book/builds/394557746#L461 for example

**Comment by fitzgen** [comment]
I think it would be wonderful to put this info into a section of the user guide so that it is discoverable for a wider audience. Happy to send a PR if you tell me where it should go.

**Comment by mattico** [comment]
The [mdBook user guide](https://rust-lang-nursery.github.io/mdBook/) is the [book-example in this repo](https://github.com/rust-lang-nursery/mdBook/tree/master/book-example). I'm sure this information could live in there somewhere.

**Comment by fitzgen** [comment]
Fix over at https://github.com/rust-lang-nursery/mdBook/pull/715
