### ISSUE TITLE
"mdbook test" stopped working with 0.1.8

### ISSUE THREAD

**Issue by RalfJung** [rust-lang-nursery/mdBook#724]
The update from 0.1.7 to 0.1.8 broke `mdbook test` in [the nomicon](https://github.com/rust-lang-nursery/nomicon). It now fails with
```
2018-07-16 14:41:02 [ERROR] (mdbook::utils): Error: Unable to open the file
2018-07-16 14:41:02 [ERROR] (mdbook::utils): 	Caused By: No such file or directory (os error 2)
```
I am not sure which file it is even trying to open (the error is not very helpful), but strace indicates it is some `index.md`:
```
stat("/home/r/src/rust/nomicon/src/index.md", 0x7fff52e9e770) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/r/src/rust/nomicon/src/index.md", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```
The nomicon works fine with mdbook 0.1.7 (well, there is a test failure but we are getting much further than the error it shows with 0.1.8). Also see https://github.com/rust-lang-nursery/nomicon/issues/78.

I believe this is a bug in mdbook because the update claims to be semver-compatible but, as this example shows, it is not.

**Comment by RalfJung** [comment]
Thanks. :)

Would you mind giving a heads-up when a new release is made with this? Then I can update the nomicon to no longer pin an older version.

**Comment by mattico** [comment]
Sure thing! I'll make a new release as soon as I get crates.io permissions.

**Comment by Michael-F-Bryan** [comment]
@mattico I just did the `cargo owner --add` thing, so you should receive some sort of ownership invitation from crates.io soon.

**Comment by mattico** [comment]
Thanks @Michael-F-Bryan!

@RalfJung 0.1.9 is on crates.io, and binaries should be available soon.

**Comment by RalfJung** [comment]
Thanks! I updated the nomicon.
