### ISSUE TITLE
binary releases are awesome

### ISSUE THREAD

**Issue by warpfork** [rust-lang-nursery/mdBook#725]
Hey all, mdBook is awesome.

And as a consumer of the tool who happens not to work on rust on a regular basis, the binary releases are also awesome, and I want to say thanks for those.

I'll also be really excited when the recent stuff gets into another binary release.  The last one seems to have been 1.5 -- a couple tags have happened since then, but without binaries, it's a little hard to get at without managing a rust compiler installation.  Especially I can't wait to see the latest [#603 features](https://github.com/rust-lang-nursery/mdBook/commit/bdb37ec117a05677dc9f35df7a0f619e8f768153) become easily available :)

Cheers!

**Comment by mattico** [comment]
Agreed! There was a bug in the travis deploy script which prevented release archives from being uploaded, which should be fixed now. I'll upload binaries for the affected releases (the ones I can build locally, at least).
