### ISSUE TITLE
Subsection titles not wrapping properly?

### ISSUE THREAD

**Issue by mark-i-m** [rust-lang-nursery/mdBook#729]
It looks like subsection titles just get cut off, rather than wrapping. See the screen shot in https://github.com/rust-lang-nursery/rustc-guide/issues/172.

Is this a known issue? Is it something we are doing wrong?

**Comment by mattico** [comment]
You're certainly not doing anything wrong, this is a CSS bug. I'm not a CSS guru, but I'll see if I can fix it.
