### ISSUE TITLE
mdbook build creates broken links in v0.1.9

### ISSUE THREAD

**Issue by cauebs** [rust-lang-nursery/mdBook#746]
If you use `mdbook serve`, it will work fine. v0.1.8 also works fine.

**Comment by mattico** [comment]
Can you give an example of a book/link which does not work correctly? Things seem to work fine for me.

**Comment by mattico** [comment]
Yes, I see the issue now. For some reason the book uses `../` as its path_to_root, from the changes in #603.

**Comment by mattico** [comment]
Okay, found the bug. `index.html` is generated from the first chapter, which in this case is in a subdirectory. The `path_to_root` is `../` to escape the subdirectory but `index.html` is rendered into the root. This function was not updated by #603:

https://github.com/rust-lang-nursery/mdBook/blob/b5fd170008085720815489e984bc9699fdb0423b/src/renderer/html_handlebars/hbs_renderer.rs#L102-L106

**Comment by mattico** [comment]
Hmm, I thought that #603 was included in 0.1.8, but it's actually first in 0.1.9. I thought that #603 was backwards-compatible modulo bugs, but after reading it again, it is not. Any link relative to the book root will break, and many existing books use these. Therefore, I'm going to yank 0.1.9 and 0.1.10 to follow semver. I'll release a 0.2.0 from master shortly after.
