### ISSUE TITLE
Publish OSX Binary

### ISSUE THREAD

**Issue by rbuckland** [rust-lang-nursery/mdBook#763]
The OSX Binary release is missing from 

https://github.com/rust-lang-nursery/mdBook/releases

It was removed as part of OSX Build failures #549

But erroneously the `README.md` suggests that Linux and OSX are built (Build status at the top)

**Comment by mattico** [comment]
Yes, I have no way to build these locally but I do intend to get CI releases working again.

**Comment by badboy** [comment]
I think it's still best and easiest to rely on `trust` for easy compilation on the required platforms (probably x86_64 and i686 linux as well as x86_64 macos)

@mattico:
Would you be ok with bringing back `trust` again to enable linux and mac builds? I'd be happy to send a PR.

**Comment by ehuss** [comment]
Macos builds are working again in the latest release: https://github.com/rust-lang-nursery/mdBook/releases/tag/v0.3.0
