### ISSUE TITLE
[Question] Are there release notes available?

### ISSUE THREAD

**Issue by idubrov** [rust-lang-nursery/mdBook#766]
I noticed my book became broken with newer release, so I got curious why. Is there any way to find what was changed between different releases?

Thanks.

**Comment by mattico** [comment]
Release notes are available on recent GitHub releases: https://github.com/rust-lang-nursery/mdBook/releases

**Comment by idubrov** [comment]
Oh. Sorry! Looked everywhere, but in releases :)
