### ISSUE TITLE
robots.txt entry for print.html?

### ISSUE THREAD

**Issue by phansch** [rust-lang-nursery/mdBook#772]
I just came across a google result from the rustdoc documentation that points directly to the `print.html`: https://doc.rust-lang.org/rustdoc/print.html.

Would it make sense for mdbook to include a robots.txt in the generated output that prevents crawlers from indexing `print.html`?

**Comment by killercup** [comment]
Yes, alternatively add `<meta name="robots" content="noindex" />` to the `print.html`'s header.

**Comment by phansch** [comment]
I didn't know that it's possible to manage robots via meta tags, nice!
