### ISSUE TITLE
Section numbers are off by one after horizontal rules

### ISSUE THREAD

**Issue by fitzgen** [rust-lang-nursery/mdBook#779]
If one has this `SUMMARY.md`:

```markdown
# Summary

- [Chapter 1](./chapter_1.md)
--------------------------------------------------------------------------------
- [Chapter 2](./chapter_2.md)
--------------------------------------------------------------------------------
- [Chapter 3](./chapter_3.md)
```

then one ends up with this bogus section numbering:

![numbering](https://user-images.githubusercontent.com/74571/45122805-cad42680-b119-11e8-971b-f12868411571.png)

**Comment by fitzgen** [comment]
If someone could drop some pointers for me in here, I would be happy to try and whip up a fix :)

**Comment by mattico** [comment]
My first suggestion would be to see if this happens with upstream [pulldown-cmark](https://github.com/google/pulldown-cmark). I can't think of anywhere in mdbook itself that is likely to cause this at the moment, but hopefully I can be more helpful if it's not a bug in pulldown-cmark.
