### ISSUE TITLE
Links to resources in subfolders are not rewritten in index.html and print.html

### ISSUE THREAD

**Issue by sam701** [rust-lang-nursery/mdBook#789]
Here is my directory structure
```
SUMMARY.md
dir1/
  content.md
  picture.png
```

There is a link to `picture.png` in `content.md`:
```
![my picture](./picture.png)
```

After `mdbook build` these files contain `<img src="./picture.png" alt="my picture">`
* `book/index.html`
* `book/print.html`
* `book/dir1/content.html`

This is correct for `content.html` but not for `index.html` and `print.html`. The image is not shown.

**Comment by MihaZupan** [comment]
Can confirm, images are broken when printing.
