### ISSUE TITLE
Partial include of code snippets and examples using anchors

### ISSUE THREAD

**Issue by CBenoit** [rust-lang-nursery/mdBook#811]
It's already possible to perform partial includes as described in [the book](https://rust-lang-nursery.github.io/mdBook/format/mdbook.html#including-files). However, it's only feasible by specifying specific lines to include. The issue is that when lines are added or removed, the book is broken without notice.

One way to avoid this that I can think of is `anchor`.
For instance:

```
/// ANCHOR: component
struct Paddle {
    hello: f32,
}
/// ENDANCHOR: component

/// ANCHOR: system
impl System for MySystem { ... }
/// ENDANCHOR: system
```

Then to perform the partial include in the book, something like:

```
We now define our component:

{{#include file.rs:component}}

Then our system:

{{#include file.rs:system}}
```

I think this would be a great way to improve maintainability.

**Comment by Moxinilian** [comment]
I'd love to see something like this, maybe with a different syntax to not confuse it with documentation.

**Comment by CBenoit** [comment]
Great! I would be glad to take this opportunity.

**Comment by CBenoit** [comment]
Done! See https://github.com/rust-lang-nursery/mdBook/pull/851
