### ISSUE TITLE
Publish assets for >= v0.2.2 release?

### ISSUE THREAD

**Issue by jamesmunns** [rust-lang-nursery/mdBook#820]
Currently, there is a v0.2.2 release in https://github.com/rust-lang-nursery/mdBook/releases, however there are no binary assets associated with it. This causes a common pattern of "check for the latest release, and install with `trust`" to fail.

Could you please upload the assets for v0.2.2?

For the embedded working group, we've worked around this by pinning our CI to use v0.2.1, but we would like to revert this change. See here for the pattern I am referring to, and our workaround at the moment:

https://github.com/rust-embedded/book/blob/master/ci/install.sh#L4-L12

**Comment by jamesmunns** [comment]
CC the following Rust Embedded issues where this issues is seen:

* https://github.com/rust-embedded/book/issues/59
* https://github.com/rust-embedded/docs/issues/8
* https://github.com/rust-embedded/embedonomicon/issues/32
* https://github.com/rust-embedded/discovery/issues/137

**Comment by konstin** [comment]
Looks like [ci failed](https://travis-ci.org/rust-lang-nursery/mdBook/jobs/443997343) due to https://github.com/rust-lang-nursery/mdBook/commit/9157f6e32dab2c7e33a9386d7c3c80b663d327f5#diff-354f30a63fb0907d4ad57269548329e3L13 @mattico

**Comment by killercup** [comment]
Just ran into this too. I'd also settle for an 0.2.3 release :)

**Comment by ehuss** [comment]
I opened PR #872 to get started fixing this.  If that gets merged, the next steps are to update the deploy API keys.

**Comment by jamesmunns** [comment]
Thanks @ehuss! Let me know if I can help with anything.

**Comment by Dylan-DPC** [comment]
@ehuss the mentioned PR has been merged

**Comment by ehuss** [comment]
Binary assets are now working in the latest release: https://github.com/rust-lang-nursery/mdBook/releases/tag/v0.3.0
