### ISSUE TITLE
Inline code is styled as display: inline-block

### ISSUE THREAD

**Issue by marijnh** [rust-lang-nursery/mdBook#821]
Besides causing #801 and #750, it also produces undesirable line wrapping behavior (punctuation after a piece of code will wrap to the next line, whereas it should stick to the word before it) and will wrap longer pieces of code _inside_ their own block, rather than along with the rest of the text.

The `display: inline-block` for code seems to have been introduced ages ago, in https://github.com/rust-lang-nursery/mdBook/commit/90719f721b20ef7096e30f27e163444d690e417f , without a clear justification in the patch.

Simply changing the `display` from `inline-block` to `inline` seems to resolve these issues without breaking anything obvious, but since CSS is the gold standard for subtle interaction and global effects, it's hard to be sure. @azerupi Do you remember why you added it?

**Comment by mrec** [comment]
In Chrome I need to both change `display` to `inline` **and** disable the `vertical-align:middle`.

**Comment by caladd** [comment]
I'll take care of this.
