### ISSUE TITLE
Project Maintenance

### ISSUE THREAD

**Issue by Michael-F-Bryan** [rust-lang-nursery/mdBook#858]
For the last 12 months or so I've been helping to maintain `mdbook`, but I'm working as a full time software dev now and things have happened in my personal life which mean I don't have as much spare time as I used to... I don't want to hold back an awesome tool like mdbook because of my lack of attention, so was wondering how other open-source groups usually go about maintainership and coordinating a long-lived project?

I'm not 100% sure who the best person to talk to, but hopefully someone from @rust-lang-nursery can point me in the right direction :slightly_smiling_face:

**Comment by CBenoit** [comment]
This is an understandable situation. Thanks for all until now.
Was there any news about that since you opened this issue?

**Comment by weihanglo** [comment]
As a contributor, if a project lacks of the dev roadmap and proper issue management, I often feel confused while figuring out which issues or pull requests are ongoing. In my opinion, just like every software development management does. A well-managed timetable and a clear priority levels of issues would help contributors be more comfortable to engage a project. Maybe we can start from making our goals of mdBook of 2019, and then categorize and label existing issues/PRs by evaluating the relevance to the goals.

By the way, I am willing to help to maintain this project.

**Comment by Michael-F-Bryan** [comment]
> As a contributor, if a project lacks of the dev roadmap and proper issue management, I often feel confused while figuring out which issues or pull requests are ongoing. In my opinion, just like every software development management does. A well-managed timetable and a clear priority levels of issues would help contributors be more comfortable to engage a project. Maybe we can start from making our goals of mdBook of 2019, and then categorize and label existing issues/PRs by evaluating the relevance to the goals.

Thanks @weihanglo, you put it into words a lot better than I could! I think this project could do with a bit more organisation. Until now we've been going along "organically", adding features or fixing bugs as we see fit. This is great for autonomy, but makes it difficult for people to contribute to the project.

@steveklabnik used to help out with commenting on PRs and acting as the go-between when transferring `mdbook` to the rust-lang-nursery, but I don't think he's working on Rust full-time any more. It'd be nice to get in contact with someone from the core Rust team to help organise things.

Here are a couple points to help us get started:

- Develop a set of goals
- Use the recently developed plugin architecture to create backends for other formats (e.g. EPUB, PDF)
- Rewrite the `mdbook test` command to just be an alternate backend instead of its own bespoke thing. It also needs to be smarter thank just invoking `rustc chapter.md --test` (for caching, using crates.io, etc)
- Refactor/rewrite the current HTML renderer to make it a lot cleaner and less like a big bowl of spaghetti
- Make it easier for people to work on multiple translations/versions of the same document (e.g. *The Book*)

**Comment by juanibiapina** [comment]
It seems like there's a lot of people not only interested, but actively contributing PRs. What is missing is just someone (or a group of people) to take care of merging those PRs. A few of them are just fixing bugs and build problems.

To me it seems this project is almost complete, in a sense that it is used in production by at least one major book. It probably doesn't need new features soon. I think it's more important to get it back to a production looking state than to think about a roadmap.

I also volunteer to help.

**Comment by mattico** [comment]
I'd encourage those that want to help to email Steve Klabnik or someone else from rust-lang-nursery to get commit access here. They don't seem to be stingy granting it which makes sense since there's limited damage one can do with it. There's a lot of good work being submitted here and not enough maintainer time to get it merged.

**Comment by steveklabnik** [comment]
I have been meaning to reply to this thread but haven't had the chance;
it's likely I will next week. Sorry for the delay. Help will certainly be
good, but I'm in the process of moving house.

**Comment by ehuss** [comment]
@steveklabnik Have you had a chance to think about this more?  I'm willing to help review/merge small changes.  Some books can't migrate to 0.2 since they are blocked on some issues here.

**Comment by Dylan-DPC** [comment]
If you need a team to maintain this, I'm ready to help

**Comment by steveklabnik** [comment]
Hey folks,

First of all, sorry for taking forever here. It turns out that moving across the country, quitting your job, and trying to get a new one means that some things fall through the cracks for a while :)

I *would* like to start a new team here to maintain mdbook. I don't have the time to do maintenance, and it's clear most of the current maintainers don't either.

Is there anyone in this thread who would like to lead this team? If so, putting together a charter would be a great first step, that is, what the future plans are for going forward.

**Comment by Dylan-DPC** [comment]
@steveklabnik I can do it but someone else wants to step in and lead I'm fine with that as well.

**Comment by weihanglo** [comment]
@steveklabnik I can also support both the maintenance and implementation works.

**Comment by yaahallo** [comment]
I don't have time to jump in and help with organizing but if you need contributors to implement PRs I'm down to help.

**Comment by carols10cents** [comment]
I don't have much time either, but as the other co-author on The Book, I'd be happy to test out PRs, provide a user perspective on any changes, weigh in on priorities, etc :) Please feel free to ping me whenever and I'll help out best I can!

**Comment by rinon** [comment]
I'm using mdBook for a project and have written some small plugins and customizations. I'd be happy to review some PRs and work on issues, but I also can't commit to coordinating maintenance right now.

**Comment by steveklabnik** [comment]
Hey folks;

So, I've just removed all the old collaborators, for a fresh start. I've invited @Dylan-DPC, so that they can merge PRs. The first step will be going through all the open PRs, then looking at Issues, and once we have taken stock of where we're at, we can come up with a plan for an mdbook 1.0.

If you'd like to help, please review some PRs! Anyone can review a PR on GitHub, so you shouldn't need any special access to do so, and @Dylan-DPC can merge. We'll see how this all goes and then slowly roll more people in.

**Comment by Dylan-DPC** [comment]
We are good at this stage, though a few more maintainers would be helpful. If anyone is reading this and interested in maintaining, just leave a comment here even though it is closed. Thanks

**Comment by weihanglo** [comment]
I am interested in maintaining works, though need some instructions and guidance.

**Comment by Dylan-DPC** [comment]
@weihanglo sure. is there any other place i can contact you (e.g. discord)
