### ISSUE TITLE
serve: after reload, 404 not found

### ISSUE THREAD

**Issue by lizr2004** [rust-lang-nursery/mdBook#862]
After modifying a source file, `ws://localhost:3001` will send "reload", but browser will reload quickly, before mdbook is ready, and report a 404. Manually reload can fix it.

suggestions:
- after receive "reload", sleep for a while, then reload.
- send "reload" after generating pages

<del>(poor English)</del>

**Comment by lizr2004** [comment]
After reading the source code, I think problem can't because of this...

But why... :(

**Comment by sdball** [comment]
Can you provide some steps to reproduce the problem and which OS/browser you're using? When I tried this from book contents running from `mdbook serve` my open Firefox browser reloaded the page contents without any 404 errors.

**Comment by lizr2004** [comment]
Archlinux with kernel 4.20 
chromium `71.0.3578.98 (Official Build) Arch Linux (64-bit)`
mdbook `v0.2.1`

It didn't work last week but works fine now...
So, the triggering conditions are unknown and close this issue now...
when the bug reappears, I'll report/reopen again
Thanks!

**Comment by lizr2004** [comment]
If I do it for only one document, it works. When plenty of documents are wrote to the disk, it can trigger this 'bug'.

**Comment by lizr2004** [comment]
```
F1w-------------------F2w---------------
--Build F1--------------Build F2--------
----WebSocketReload-------Refresh-404---
```
Like this?
