### ISSUE TITLE
There is no next page button 

### ISSUE THREAD

**Issue by rerime** [rust-lang-nursery/mdBook#874]
At this pages
https://rust-lang-nursery.github.io/cli-wg/index.html
https://rustwasm.github.io/book/
https://rust-embedded.github.io/book/

**Comment by Lokathor** [comment]
There seems to be a problem with both the top level URL as well as the "introduction" page without the chapter number on it (if any), not getting the next buttons.

Compare:
* https://rust-lang.github.io/rust-bindgen/
* https://rust-lang.github.io/rust-bindgen/introduction.html

**Comment by ccharles** [comment]
Is this actually fixed?

I'm seeing the same behaviour with mdBook v0.3.1, which [contains the merged commit][1] from #916:

- `http://my-book/` has no navigation ❌
- `http://my-book/index.html` has no navigation ❌
- `http://my-book/any-page.html` has navigation ✔️

[1]: https://github.com/rust-lang-nursery/mdBook/commit/a674c9eff158d37048d5d70c0fe3b71f2c9800c2

**Comment by ehuss** [comment]
@ccharles Thanks, I'm not sure what happened, somehow I botched the fix. I posted a new fix at #1005.

**Comment by ccharles** [comment]
Awesome, thanks for tackling this so quickly @ehuss!
