### ISSUE TITLE
Including other files between some start and end string

### ISSUE THREAD

**Issue by chinedufn** [rust-lang-nursery/mdBook#879]
Right now you can include the contents of a file in between two line numbers.

---

This has been useful - but can lead to some rot if you modify a file and forget to update your mdbook.

---

That rot has led me to sometimes split some code into another file - not because I wanted to or thought that it made sense - but because I wanted to be able to include it into an mdbook without forgetting to update the include statement.

---

I'm thinking that it would be useful to be able to include between some start and end sequence

Here's a rough sketch:

```rust
fn main () {
  // Include this in the book
 let hello = "68656c6c6f";
 let world = "776f726c64";
 // Ok, all done!
}
```

```rust
{{ #include /path/to/file.rs:"Include this in":"Ok, all done!" }}
```

---

Could certainly be done in a third-party plugin - but I'm thinking that something like this might be useful enough to include in core...?

Rough ideas above so.. any thoughts are appreciated!

**Comment by chinedufn** [comment]
Another thing that would be useful is being able to start from some string and then end at some offset number of lines.

```
{{ #include /path/to/file.rs:"Include this in":+10 }}
```

So this would start at the first line that contained `"Include this in"` and end at that line number +10 (or end of file if there aren't 10 more lines)

**Comment by chinedufn** [comment]
Made a preprocessor for this `mdbook-superimport` https://github.com/tailwind/mdbook-superimport/pull/1

**Comment by CBenoit** [comment]
An issue and pull request was already open: https://github.com/rust-lang-nursery/mdBook/pull/851 and https://github.com/rust-lang-nursery/mdBook/issues/811
But your `mdbook-bookimport` is a great replacement while we wait for a new maintainer! :+1:

**Comment by chinedufn** [comment]
Ohhhh awesome thanks for the links!
