### ISSUE TITLE
mdbook build run into an error

### ISSUE THREAD

**Issue by HobDev** [rust-lang-nursery/mdBook#881]
I install the mdbook with terminal. Thereafter run the command `mdbook build`. But it through  the following error:
2019-03-03 18:31:32 [ERROR] (mdbook::utils): Error: Couldn't open SUMMARY.md
2019-03-03 18:31:32 [ERROR] (mdbook::utils): 	Caused By: No such file or directory (os error 2)
I runt the `mdbook build` command on my home directory.  I am on MacOS Mojave 10.14.3.

**Comment by mrec** [comment]
Did you run [`mdbook init`](https://rust-lang-nursery.github.io/mdBook/cli/init.html) first to set up the book's skeleton? Or specify a [path to your book directory](https://rust-lang-nursery.github.io/mdBook/cli/build.html#specify-a-directory) if you already have a book project somewhere else?

**Comment by HobDev** [comment]
@mrec  I get to build the book giving the correct path. Sorry for the raising such a issue.
