### ISSUE TITLE
Clearing highlights after performing a search

### ISSUE THREAD

**Issue by yaymukund** [rust-lang-nursery/mdBook#884]
Moved from https://github.com/rust-lang/book/issues/1847

After searching for a very common term, the highlights can make it difficult to actually read the text. It would be nice to have an easy way to clear the highlight.

![screenshot-2019-03-08-02-03-11](https://user-images.githubusercontent.com/590450/54024143-bbc34500-414b-11e9-8f2a-926f186c9d79.png)

Currently, you have to delete the `?highlight=` argument in the URL. Perhaps hitting `Esc` could remove the highlight and update the URL? Or the search input could remain on the page, with an `X` to clear it?

**Comment by ehuss** [comment]
Pressing [escape](https://github.com/rust-lang-nursery/mdBook/blame/c068703028d19fb6c5a4690e904ae6f2bd74292f/src/theme/searcher/searcher.js#L316-L325) should clear the highlight.

**Comment by yaymukund** [comment]
@ehuss that works as you're searching, but not once you've clicked through to a search result. For example, [you can't hit `Esc` to clear the highlight on this page](https://doc.rust-lang.org/book/ch19-06-macros.html?highlight=macro#macros)

**Comment by ehuss** [comment]
Esc works for me on that page. Which browser/version/platform are you on?

**Comment by yaymukund** [comment]
Ah! It was an extension getting in the way. My mistake. Thank you for helping debug :sweat_smile:

**Comment by runiq** [comment]
Would you consider adding a UI element for clearing the highlights? I cannot remove them on mobile without editing the URL.

**Comment by ehuss** [comment]
@runiq sounds like a good idea, can you file a new issue?  Also, maybe some suggestions on how it should work.  It probably doesn't need to be mobile-specific because `Esc` is not always discoverable.  Even better if you can point to some popular sites that do something similar.  (I know [python](https://docs.python.org/3/library/os.html?highlight=os) does, but I don't see *any* way to clear the highlight.)

**Comment by runiq** [comment]
@ehuss Done: https://github.com/rust-lang/mdBook/issues/1117
