### ISSUE TITLE
Improve theme for highlighting toml config

### ISSUE THREAD

**Issue by lzutao** [rust-lang-nursery/mdBook#890]
From https://doc.rust-lang.org/nightly/cargo/reference/config.html#configuration-keys
![image](https://user-images.githubusercontent.com/15225902/54774412-44f37500-4c3e-11e9-83db-9637336bd63f.png)

**Comment by lzutao** [comment]
To test highlighter.js and prism syntax highlighter, I wrote this gist:
https://gist.github.com/lzutao/f5513a5d9a122d1cbf846f2f097fad7f

Screenshot of that gist:
![image](https://user-images.githubusercontent.com/15225902/58332457-74ed0d80-7e65-11e9-98da-4a16a0b794d4.png)

**Comment by lzutao** [comment]
cc highlightjs/highlight.js#2040

**Comment by ehuss** [comment]
I already opened a hljs PR a few days ago: https://github.com/highlightjs/highlight.js/pull/2039

**Comment by lzutao** [comment]
Glad to know that! Looking forward for you PR to beging merged.
