### ISSUE TITLE
Library depends on `same-file`

### ISSUE THREAD

**Issue by FreeMasen** [rust-lang-nursery/mdBook#902]
Currently even the library associated with this project will require that it is compiled on either unix-like or windows target because of a transitive dependency. `same-file` is a dependency of `walkdir` which has 2 architecture dependent implementations of it's functionality. While the direct dependency on `walkdir` is in the `dev-dependencies` section, which would avoid any issues for users of the mdbook library, it happens to be a dependency of `handlebars` as well. The `handlebars` crate has a feature gate to remove this depenency (`no_dir_source`) which would remove this problem.  

According to the unit tests adopting this feature shouldn't break anything.

**Comment by Dylan-DPC** [comment]
Fixed by PR linked (#903). Thanks
