### ISSUE TITLE
Setting up automatic deploy.

### ISSUE THREAD

**Issue by ehuss** [rust-lang-nursery/mdBook#904]
The current API keys are no longer valid, so deploy is currently broken. This is needed for cargo and the rust-lang reference to update. It is also needed to keep the gh-pages documentation up-to-date.

Someone with write access to the `rust-lang-nursery/mdBook` repository (and maybe Travis and Appveyor) needs to generate the new token. I'm not sure if this is the best process, but this appears to be how to set it up:

### Create GitHub OAuth Token

This generates an OAuth token with full write access for the user. If you are not comfortable giving Travis and Appveyor access to all of your repositories, then a rust-lang-nursery admin will need to create a "machine user" which only has access to `rust-lang-nursery/mdBook`. This is generally preferred, but more work. Then the following steps would need to be done for that new user.

1. Create an OAuth token on the GitHub website. Follow the steps in https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line. Essentially, go to https://github.com/settings/tokens and click "new". The name doesn't matter, "mdBook deploy" would be fine. Check the `repo` (`public_repo`) checkbox and no others. Copy the token for the next steps, but otherwise be careful not to leak it anywhere. It is needed for both Travis and Appveyor.

### Travis release deployment and gh-pages

1. Make sure you have the `travis` command-line client installed.  See: https://github.com/travis-ci/travis.rb#installation
2. I *think* you need to login first: `travis login --com`.
3. Encrypt the OAuth token for Travis: `travis encrypt --com`.
    3a. When it says "Reading from stdin…", type: `GITHUB_TOKEN=…paste token here…` with the GitHub OAuth token, press enter, then Ctrl+D.
4. Copy the encrypted string into `.travis.yml` as an environment variable. It should look something like this:

   ```yml
   env:
     global:
        # GITHUB_TOKEN — This is the encrypted OAuth token for deployment.
        - secure: …encrypted string here…
   ```
5. Change deploy/api_key in `.travis.yml` to look like this:
   ```yml
   deploy:
     api_key: "$GITHUB_TOKEN"
   ```

6. So the documentation stays up-to-date, the pages deploy needs to be set up. A new deploy provider needs to be added, along with a step to actually build the docs. The changes to `.travis.yml` should look like this:

    ```diff
    diff --git a/.travis.yml b/.travis.yml
    index 908be6034..5c2b0e878 100644
    --- a/.travis.yml
    +++ b/.travis.yml
    @@ -22,6 +22,8 @@ before_cache:

     env:
       global:
    +    # GITHUB_TOKEN — This is the encrypted OAuth token for deployment.
    +    - secure: …encrypted string here…
         - CRATE_NAME=mdbook

     script:
    @@ -29,18 +31,25 @@ script:
       - cargo test --all --no-default-features

     before_deploy:
    +  - cargo run -- build book-example
       - sh ci/before_deploy.sh

     deploy:
    -  provider: releases
    -  api_key:
    -    - secure: cURRWBr034iqBz/ifD7uOunBfNR30YxIXfgLX0osWz+iafkVbhDGYYz9sBmRraqO2P7L2koEXMADVb/md1kI2+ykiq/ml+l9zuEAZPVmvSGUN7ZD+7s+lu3l5OBPG5z175T+b2q2q2m8XVR7TW20ra4QbE0bq06KAoOyjSgQVBTSCYsL9uTsGwiVRMEqqJT/BmKhKJNkpGsTKyBSKkOXvfeAAbE260vXUDEN9TYdJ3fvteRrpwLX56ee64gIZUq0RjDc4SKIEqilM6iUtNMvurqaewYNGkiXKRruV6BPCHxEHo6NNT46kOJLBJTf7gZw//dWhSoWpg9P0gdAnPWm407kSa3F7aJ1eRShAFQ4BLyfz9efTqm+jP3fOp7Mm7igSh9w6caSRuOnSsUf5+raRQ8E5Y9HsWGzzpZQk24Fx9EGZ04EeDSdpZAFz+jcbMpHf8t2p4CEx0CCNwYvKx6EydMKbMF5QteQ8SQkXNLhv7Rz2OgtXWYZPRVCMfQfOplsi2InsLCrQxTgwh+6u654SqVSgaHG+IncEAxBrdWy4rHcg7qereUcKfcY3k96vaDxdn/T2c00Ig0aNFR91YnixGMd6J6tQgDcRK9jh6fUm1CCBE9hT+pNUmtgYKuWBoLZexUZFFnfuBed0WciBot1bGDDamndqKq0jJiAzg+GMHk=
    -  file_glob: true
    -  file: "$CRATE_NAME-$TRAVIS_TAG-$TARGET.*"
    -  on:
    -    condition: "$TRAVIS_RUST_VERSION = stable"
    -    tags: true
    -  skip_cleanup: true
    +  - provider: releases
    +    api_key: "$GITHUB_TOKEN"
    +    file_glob: true
    +    file: "$CRATE_NAME-$TRAVIS_TAG-$TARGET.*"
    +    on:
    +      condition: "$TRAVIS_RUST_VERSION = stable"
    +      tags: true
    +    skip_cleanup: true
    +  - provider: pages
    +    local_dir: book-example/book
    +    skip_cleanup: true
    +    github_token: "$GITHUB_TOKEN"
    +    keep_history: true
    +    on:
    +      branch: master

     branches:
       only:
    ```

7. Commit `.travis.yml` and push it (or make a PR).

### Appveyor release deployment

1. Go to https://ci.appveyor.com/tools/encrypt.  I think this needs to be done with an Appveyor account that has access to the mdBook repo, appveyor permissions have always been a mystery to me.  
2. Paste the GitHub OAuth token in to encrypt it.
3. Copy the encrypted string into `appveyor.yml` in the `deploy/auth_token/secure` section.
4. Commit `appveyor.yml` and push it (or make a PR).

**Comment by carols10cents** [comment]
I might have some of the right permissions, I can certainly try.

> This is needed for cargo and the rust-lang reference to update.

I'm a bit confused why mdbook needs to be able to deploy its docs in order to update cargo and the reference? Can you elaborate please?

**Comment by carols10cents** [comment]
In looking at [0.2.3's tagged build logs](https://travis-ci.com/rust-lang-nursery/mdBook/jobs/171456705#L934), it's erroring on the missing target, [which it looks like you fixed](https://github.com/rust-lang-nursery/mdBook/commit/966632a724a396007d7e5e52d007008dbb6c465f#diff-354f30a63fb0907d4ad57269548329e3). 

Are you sure it's a permission issue now? Am I looking in the wrong place for logs?

> It is also needed to keep the gh-pages documentation up-to-date.

[It looks like the gh-pages deploy was removed](https://github.com/rust-lang-nursery/mdBook/commit/93af92910ad62a80420e4ef5695b910a102f34b6#diff-354f30a63fb0907d4ad57269548329e3)?

**Comment by carols10cents** [comment]
ok I see this is for uploading release artifacts

**Comment by carols10cents** [comment]
> Create GitHub OAuth Token

It looks like we can use [a deploy key](https://developer.github.com/v3/guides/managing-deploy-keys/#deploy-keys) instead of oauth?

**Comment by carols10cents** [comment]
ugh that's what the github docs say, but not the travis docs....

**Comment by carols10cents** [comment]
I'm out of time to spend on this for the moment; if someone else with the right permissions comes along and feels more confident about what needs to be done, please go ahead and take this.

If that doesn't happen, I'll check back in next time I have a few minutes, not sure when that'll be.

I'm currently stuck at really really wanting to use deploy keys because they only give access to one repo and are tied to that repo, rather than giving an oauth token that's tied to my account and would have access to all the repos i have access to.

However, the docs on setting up release artifact deploy from travis and appveyor using a deploy key are lacking. I've found random gists and blog posts, which aren't exactly confidence inspiring, and i don't have time right now to assess their validity:

- https://github.com/alrra/travis-scripts/blob/master/docs/github-deploy-keys.md
- https://medium.com/@simon.legner/deploy-to-github-pages-using-travis-ci-and-deploy-keys-db84fed7a929
- http://markbucciarelli.com/posts/2019-01-26_how-to-push-to-github-from-travis-ci.html

**Comment by ehuss** [comment]
Thanks for taking a look!

> why mdbook needs to be able to deploy its docs in order to update cargo and the reference

This is for using pre-built binaries ([cargo](https://github.com/rust-lang/cargo/blob/85b4221a58cce743c937966ae934be966643c3a8/.travis.yml#L30), [reference](https://github.com/rust-lang-nursery/reference/blob/94ad2b83b473082706113cf9d74974d385464f42/.travis.yml#L7)).  At least in Cargo, we couldn't really afford the extra CI time to build mdbook every time, and caching doesn't work well enough.

When travis moved to travis.com, I believe the encryption keys changed, and `.travis.yml` hasn't been updated since.  I'm also not sure whose token was being used previously, but it's likely no longer valid. I'm not 100% sure why appveyor stopped working, but the error says the token is no longer valid.

> It looks like the gh-pages deploy was removed?

Yea.  The alternative would be to manually update gh-pages during each release.  But it looks pretty easy to support via Travis (the diff above works for my clone).

>  rather than giving an oauth token that's tied to my account

I agree using your account with an OAuth token is probably not the best choice.  I'm not sure who has admin access for rust-lang-nursery, but a "machine user" would probably be safer.  

I'll also take a look at using SSH deploy keys when I get a chance.  I have no experience with that, but as you discovered, there's not much documentation on how to do it.

**Comment by ehuss** [comment]
I took another look.  AFAIK, deploy keys don't work for creating releases, since that requires the GitHub API.  I think the best (only?) option here is to create a dedicated github user with write access to this repo only.

**Comment by ehuss** [comment]
Automatic deploy is now working. There is now a dedicated account (`rust-mdbook-deploy`) and both gh-pages and releases seem to be working.
