### ISSUE TITLE
Prev/Next keyboard shortcuts not working properly

### ISSUE THREAD

**Issue by brainplot** [rust-lang-nursery/mdBook#910]
Hi, I'm currently reading the book _The Rust Programming Language_ and I decided to build it from source checking out the latest version from [the official repository](https://github.com/rust-lang/book).
I installed mdBook via `cargo install mdbook` - without specifying any version number - and I got `mdBook v0.2.3`; then I opened the book in my browser with:
```bash
mdbook build --open
```
and I immediately noticed that the left and right arrow keys weren't working as they're supposed to.
I find those shortcuts really convenient since I try to avoid taking my hands off the keyboard as much as possible.

Almost as a desperate attempt to get those shortcuts working, I tried to install `mdbook` directly from this repository with the following command:
```bash
cargo install --git https://github.com/rust-lang-nursery/mdBook.git mdbook
```
with no luck. It produced a better looking book but those keyboard shortcuts were still not working :)

**P.S.** I should mention that in the [online version](https://doc.rust-lang.org/book/) of the book, those same keyboard shortcuts allow me switch between pages properly so I don't think it's a problem with my environment or browser.
The shortcuts also work properly for the book that opens up when I run:
```bash
rustup doc --book
```

**Comment by carols10cents** [comment]
Hi! This sounds like an issue with mdbook, could you refile this issue in the https://github.com/rust-lang-nursery/mdBook repo please? Thanks!

**Comment by brainplot** [comment]
> could you refile this issue in the https://github.com/rust-lang-nursery/mdBook repo please?

@carols10cents I'm confused. Isn't this the exact same repository you linked?

**Comment by carols10cents** [comment]
LOL oops!!!! I was on mobile, and because you talked about the book so much, I thought your issue was filed against https://github.com/rust-lang/book, which I also get emails for. You are absolutely correct, I'm sorry for incorrectly closing this!

**Comment by brainplot** [comment]
Don't worry, it happens! :)
I talked about the book to give a bit of context on what I tried and what wasn't working.

**Comment by carols10cents** [comment]
Yes, thank you for that, it is very helpful :) My brain just wasn't working ;)
