### ISSUE TITLE
I can't see my website without pointing directly to the index.html file (github pages)

### ISSUE THREAD

**Issue by oren** [rust-lang-nursery/mdBook#930]
Why can't I see my website? I am using github pages and I used the build command to generate it. I am able to see other mini sites I am hosting under the same repo.

This doesn't work:
http://oren.github.io/surf2

This works:
http://oren.github.io/surf2/index.html

The code:
https://github.com/oren/oren.github.io/blob/master/surf2/index.html

**Comment by ehuss** [comment]
The link at http://oren.github.io/surf2 works for me. What are you seeing? Which browser are you using? Perhaps github had a delay getting the page up? Or maybe you need to flush your browser cache?

**Comment by oren** [comment]
It's working now. Probably a cache issue. Thank you
