### ISSUE TITLE
Add back missing binary release or cut a patch release

### ISSUE THREAD

**Issue by badboy** [rust-lang-nursery/mdBook#949]
Hey,

can you please add binary releases for the currently stable version or cut a new patch release to generate a new binary?
I saw that the deploy of v0.2.3 failed, but the cause was fixed afterwards.

We're relying on mdbook for our documentation.
Unfortunately we're running into a bug with v0.2.1 (the last binary release) and now need to rebuild mdbook on CI all the time.
Relying on a binary release would cut down our CI time quite a bit.

**Comment by ehuss** [comment]
Hi! Maintainership has transitioned to new people, and we're just waiting to get ownership on crates.io to publish a new release. As soon as that is set up, we'll publish a new release.

**Comment by badboy** [comment]
Perfect! Thanks for the quick turnaround.
