### ISSUE TITLE
Select default theme

### ISSUE THREAD

**Issue by tekjar** [rust-lang-nursery/mdBook#95]
Hi. Is it possible to select a theme during init?

**Comment by azerupi** [comment]
You mean picking the default theme or adding a custom one?
It's not yet possible to choose which theme will be the default, but it shouldn't be to hard to add that option to the `book.json` configuration file.

**Comment by kteza1** [comment]
Yeah. I mean the default theme. For example I want my book to be in 'rust' theme by default.

**Comment by azerupi** [comment]
Ok, I have added this to the wishlist I will try to add this option when I am done with my exams in two weeks :)

**Comment by kteza1** [comment]
Thanks :+1: . All the best for your exams

**Comment by azerupi** [comment]
Thank you :blush:

**Comment by Michael-F-Bryan** [comment]
This sounds like a nice first contribution for someone and I'd be more than happy to help with mentoring if need be.

It sounds like you'll need to do the following:

- Add an extra field to the `HtmlConfig` which specifies the default theme
- Tweak the `index.hbs` template so you can specify the default theme. 
  - An easy solution would be to add an extra `<script>` tag at the bottom which will set the theme to our default if it hasn't already been specified in previous visits (there may be more elegant solutions).
- Update the config format's documentation to mention the new key in `book.toml`.

**Comment by DeltaManiac** [comment]
I'd like to work on this issue.

**Comment by Michael-F-Bryan** [comment]
@DeltaManiac awesome! Would you like a hand getting started or finding your way around the code base?

**Comment by DeltaManiac** [comment]
@Michael-F-Bryan 
So i have been going through the code and have an idea of whats is going on but it would be great if yoy could give a hand.

**Comment by Michael-F-Bryan** [comment]
Sure thing! The easiest way would probably be to open a pull request and prefix its name with something like "WIP" so we know not to merge it. 

That way we've got a place to discuss and can review what you've done without spamming this issue. How does that sound?

**Comment by DeltaManiac** [comment]
Yeah thats cool.
Will do...

**Comment by Bassetts** [comment]
It seems like this is no longer being worked on, am I ok to pick this up? Thought I should check before going ahead so I don't step on anyone's toes.

**Comment by Michael-F-Bryan** [comment]
As long as @DeltaManiac is okay with it, i don't see why you can't pick up the issue. The discussion in rust-lang-nursery/mdBook#497 should also contain enough information to help get you started.

**Comment by DeltaManiac** [comment]
@Bassetts You can go ahead.. 
This issue had totally slipped my mind somehow
