### ISSUE TITLE
sccache broken in CI

### ISSUE THREAD

**Issue by ehuss** [rust-lang-nursery/mdBook#957]
I've noticed that caching seems to be broken on CI.  The `custom_preprocessors` test runs `cargo run --example nop-preprocessor` several times for different tests.  Each time it runs, it rebuilds mdbook from scratch, which takes a very long time.

I cleared the caches on Travis, which seemed to fix it temporarily, but it is breaking again.  Here is an example: https://travis-ci.com/rust-lang-nursery/mdBook/jobs/209111625

@lzutao Can you fix this, or remove the use of sccache?  I personally don't feel like the extra complications from sccache or worth it, but perhaps there is a simple fix.

**Comment by lzutao** [comment]
I will try to build with latest mdbook from git to reproduce it.

**Comment by lzutao** [comment]
I believe the issue should be fixed on latest sccache. We could choose to build sccache
from source, or temporary use my prebuilt version, or call for new sccache release.
