### ISSUE TITLE
Link to "create issue" for Runnable Rust snippets.

### ISSUE THREAD

**Issue by bytesandwich** [rust-lang-nursery/mdBook#969]
For broken code snippets, I think a link to create an issue or notify the authors some other way would be an awesome feature.

For example here's a broken snippet in [Failure's guide](https://boats.gitlab.io/failure/fail.html#cause) that I 

<img width="778" alt="Screen Shot 2019-07-02 at 9 47 36 AM" src="https://user-images.githubusercontent.com/1048685/60530846-8a4c2780-9cae-11e9-9cc3-fb61af097b4f.png">

Could be:

<img width="786" alt="Screen Shot 2019-07-02 at 9 54 42 AM" src="https://user-images.githubusercontent.com/1048685/60531275-76ed8c00-9caf-11e9-9da0-b10492413d46.png">

**Comment by ehuss** [comment]
I don't think that is something we would want to add, since many code snippets are intentionally broken.

You can set `git-repository-url` in the config which will provide an icon with a link to your repo to file issues.  Alternatively, you can customize the theme to add whichever icons you want.
