### ISSUE TITLE
Search locally

### ISSUE THREAD

**Issue by KSXGitHub** [rust-lang-nursery/mdBook#972]
## Why?

I want to use a browser to open `file:///.../book/index.html` directly. The problem is, I cannot use the search button. This is because the web page attempts to use `fetch` to download `searchindex.json` via `file:` protocol.

## Suggestion

If `searchindex.json` is small enough (which is most cases), directly embed `searchindex.json` into a script tag within each page, and then use `HTMLScriptElement.prototype.text` in place of `fetch`.

```html
<script id='searchindex' type='text/json'>
  /* content */
</script>
```

**Comment by ehuss** [comment]
mdbook already has a fallback that uses the `<script>` tag to load the index.  https://github.com/rust-lang-nursery/mdBook/blob/3d45e4069348113ac4a6d8c18aa0115e51f078b9/src/theme/searcher/searcher.js#L468-L472

It should work for loading with `file:` urls.  What browser/platform are you using?  Are you using the latest mdbook?

**Comment by KSXGitHub** [comment]
It works. My bad.

**Comment by KSXGitHub** [comment]
BTW, since the fallback (`searchindex.js`) should work on both `file:` and `http:`, why bother use `fetch(path_to_root + 'searchindex.json')` at all?

**Comment by ehuss** [comment]
@KSXGitHub I believe it is to load it asynchronously and should be faster. The fallback is only necessary due to the CORS restrictions.
