### ISSUE TITLE
Element.createShadowRoot is deprecated and will be removed in M73

### ISSUE THREAD

**Issue by KSXGitHub** [rust-lang-nursery/mdBook#973]
Open Chrome DevTools in one of the page that is served via localhost and see this:

![deprecation message](https://user-images.githubusercontent.com/11488886/60717613-82a9ae80-9f4c-11e9-9267-6734215144d4.png)

```
[Deprecation] Element.createShadowRoot is deprecated and will be removed in M73, around March 2019. Please use Element.attachShadow instead. See https://www.chromestatus.com/features/4507242028072960 for more details.
```

**Comment by ehuss** [comment]
I don't think this warning is generated by mdbook.  I think `content.min.js` implies it is coming from one of your extensions maybe.
