### ISSUE TITLE
how to convert markdown files not list in SUMMARY.md file?

### ISSUE THREAD

**Issue by Turing-Chu** [rust-lang-nursery/mdBook#976]
Hi, I find that `mdbook` can auto convert markdown file to html file which listed in `SUMMARY.md`.

The following is an example:

```
[zxd:book_examples]$ tree 
.
├── book.toml
└── src
    ├── SUMMARY.md
    ├── chapter1_1.md
    └── chapter_1.md

1 directory, 4 files
[nobody:book_examples]$ cat src/SUMMARY.md 
# Summary

- [Chapter 1](./chapter_1.md)
[nobody:book_examples]$ cat src/chapter_1.md 
# Chapter 1

- [Chapter 1-1](chapter1_1.md)
[nobody:book_examples]$ 
```
the file `chapter1_1.md` just appare in chapter_1.md and not in `SUMMARY.md`. So when i click `chapter1_1`, it return 404 error. Is it has some method to fix this problem: mdbook can create related html file for markdown file list in user defined markdown file rather than only SUMMARY.md file?

![image](https://user-images.githubusercontent.com/13805470/60853927-c3494680-a230-11e9-9ea9-a6fee29a46c4.png)

**Comment by ehuss** [comment]
I think this has been asked for a few times, but it is currently not possible.  #830 seems to be the most relevant.

**Comment by csk111165** [comment]
Is there some workaround in 2023?
