### ISSUE TITLE
Default Fonts

### ISSUE THREAD

**Issue by srimad-bhagavatam** [rust-lang-nursery/mdBook#986]
Hello, I hope all are in good health and mood when you receive this.
I love your software! <3

How can I remove the fonts.googleapis url? Is it built into the binary? Manually deleting it is not a problem just tedious because I've been working on a massive 2GB encyclopedia, of which has only one image and the rest is text.
This is the blessing of the Supreme Person because its super fast, robust, beautiful and easy to use. Now I just need a hosting solution. 
Thank you very much for the help and this amazing software. Take care. :)

**Comment by 17cupsofcoffee** [comment]
The `link` tags for the fonts are in [`index.hbs`](https://github.com/rust-lang-nursery/mdBook/blob/master/src/theme/index.hbs) - you can [override that template](https://rust-lang-nursery.github.io/mdBook/format/theme/index.html) by making a copy of that file at `/theme/index.hbs` in your project - that'll allow you to remove the tags.

**Comment by srimad-bhagavatam** [comment]
So I can make a copy of any of the files, say a case file, edit it and it will take the effects with the next build. Thank you! I should of kept reading the manual, it was right there. I appreciate your swift response.
