### ISSUE TITLE
Mathematical formula support is terrible

### ISSUE THREAD

**Issue by 6cdh** [rust-lang-nursery/mdBook#997]
# Question

I use Katex to render Mathematical formula

```markdown
$$
E[\mathrm{cost}] = \sum_{i=0}^{n}(\mathrm{depth}_T(k_i)+1)p_i + \sum_{i=0}^{n}(\mathrm{depth}_T(d_i)+1)q_i
$$
```

It can't be displayed correctly. In fact, it is converted to the following HTML

```html
<p>$$
E[\mathrm{cost}] = \sum_{i=0}^{n}(\mathrm{depth}<em>T(k_i)+1)p_i + \sum</em>{i=0}^{n}(\mathrm{depth}_T(d_i)+1)q_i
$$</p>
```

`_` was incorrectly converted to `<em>`

Then I switched to MathJax, the result has not changed. I use `<p>` to surround `$$...$$` in source code to solve this problem. But it is not portable and redundant. Is there any other easy way to fix it?

Of course there are other issues, such as having to use `\\\\` instead of `\\` to break line, but they are easy to handle

**Comment by ehuss** [comment]
I think these are known issues.  See #400 and #662 and #651.

**Comment by 6cdh** [comment]
Wrapping the math equations with HTML tags seems to work only for block equations. For inline equations, this method doesn't work. If you write `a*b*c`, you can insert a space after `*` to render correctly such as `a* b*c` or `a * b * c`. Using HTML tag is ineffective.
